LiberTEM/LiberTEM

- scripts/bump_version
Work with @sk1p: Just write directly to the file instead of using a temporary file. Git can recover the file case of errors. Fixes #146
> Fixed Windows permission errors

- src/libertem/analysis/com.py
- src/libertem/api.py
The mask radius should be set to float('inf') if it is not given
to handle any specified center point point correctly and never cut
off any part of the frame.
Additionally, remove the unnecessary multiplication with ones
when generating the COM masks.
> COM analysis: Handle no mask radius correctly

- requirements.txt
- setup.py
- src/libertem/io/utils.py
- src/libertem/web/server.py
- src/libertem/win_tweaks.py
- tests/test_fileowner.py
The pwd module is not available on Windows and uid and gid are 0 in
stat. Implement a platform-independent function in win_tweaks.py and
restructure the listing code since we need the full path to determine
an owner on Windows.
Make pypywin32 a platform-dependent dependency for Windows to support
listing the owner.
> Portable way to determine file owner

- src/libertem/web/server.py
- src/libertem/win_tweaks.py
Attempting to determine the owner of files like C:\pagefile.sys
on Windows triggers an "Access is denied" error.
* Transform the specific Windows exception to a general IOError
in win_tweaks.py
* Handle the IOError gracefully in web/server.py
> Catch an exception on Windows and handle it gracefully

- src/libertem/executor/dask.py
- src/libertem/io/dataset/base.py
- src/libertem/io/dataset/blo.py
- src/libertem/io/dataset/hdf5.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- src/libertem/io/dataset/raw.py
Change the default behavior of `get_location()` to return `None`.
dask interprets this as "any worker".
Use `get_location()` independent of `is_local`. Verify that it is either
"None" or not empty. (thx @sk1p!)
Remove the non-functional get_locations() implementations from the
subclasses. "127.0.0.1" doesn't always work as a default identifier.
The remaining purpose of is_local is to determine if we should tidy
up the cluster or leave it running.
> Support using an external local dask cluster

- .travis.yml
- appveyor.yml
- docs/source/contributing.rst
- src/libertem/api.py
- src/libertem/executor/dask.py
- src/libertem/web/server.py
- tests/conftest.py
- tests/io/test_detect.py
- tests/test_local_cluster.py
- tox.ini
The regular startup method for a local dask cluster doesn't work
from within Digital Micrograph 3.40 beta. The new code introduces an
alternative launch method via the subprocess module.
In order to make it safe and convenient to use, include support for
context manager. Within Digital Micrograph 3.40 beta it is important to
tidy up after a script because the embedded interpreter continues to run.
A running dask cluster subprocess would block Digital Micrograph.
TODO Verify handling of all possible error states in launcher
TODO Unix compatibility: Existence of "pythonw" vs "python"
TODO Raise issue with dask/distributed if dask should use a different
launch method for local clusters that works from within embedded interpreters
TODO Proper example, tests and documentation
> Experimental subprocess launch method for cluster

- examples/digital-micrograph-basic.py
This example runs in version 3.40 beta of Gatan Digital Micrograph.
Please note that it depends on the API change in pull request #192 and the recently merged context manager and subprocess cluster startup method.
> Example that runs within Digital Micrograph

- prototypes/digitalmicrograph/components.py
- prototypes/digitalmicrograph/datashape.py
- prototypes/digitalmicrograph/digital-micrograph-async.py
Somewhere somehow the dimensions are mixed up when Digital Micrograph
constructs the image buffer numpy array.
Current workaround is a reshape of the data when writing into the buffer
This will likely change in the future when this is corrected.
> [skip ci] Bug reproducer for incorrect data shape

- src/libertem/web/server.py
Allow mixing Linux and Windows for dask cluster and libertem-server, fixes #210
With Python, '/' works on Windows as a path separator, too.
Question: Should one do some kind of logic with [os.altsep](https://docs.python.org/3/library/os.html#os.altsep) and/or asking the cluster, or do '/' and be done with it? I'd favor '/' until we have a specific case where that breaks.
> Use '/' as universal path separator.

- src/libertem/preload.py
- tests/test_smoke.py
Loading modules as part of job execution can make dask workers
unresponsive for too long. This module allows pre-loading any offenders
at the time a worker starts up.
Usage:
dask-worker [...] --preload libertem.preload [...]
Fixes #218
> Preloading for some modules

- src/libertem/api.py
Include the lesson learned from #232 in the documentation.
> Don't reference large objects in mask factories

- docs/source/conf.py
- docs/source/install.rst
Conda documentation has moved
fz-juelich.de filters the user agent string since recently. I asked them to stop filtering. Until then, fz-juelich.de is on the ignore list of the link checker as a workaround.
Refs #243
> Fix broken links

- .travis.yml
Refs #193. This is the test that no release will be built for pull requests, nor will an app image be uploaded.
> Only create continuous release from master branch

- docs/source/install.rst
This has been a major pitfall with novice users trying to set up LiberTEM for development.
Also higlight the importance of the dot when installing from a local directory.
> Include note regarding release vs dev install

- docs/source/usage.rst
sys.argv is not set in embedded interpreters https://bugs.python.org/issue32573
This workaround avoids trouble in the multiprocessing module. https://github.com/python/cpython/pull/12463
> Include workaround for sys.argv issue

- .travis.yml
- tox.ini
flake8, qa, doc building etc. should also work with Python 3.7. This is a draft PR to check if CI goes through without breaking the master build again...
> Update Python version used for CI

- prototypes/map-reduce-comparison/tiled-performance.ipynb
The difference is a result of balancing overheads from
fine-grained loops with gains from working on data that fits
the L3 cache.
Fancy indexing with the boolean mask creates a copy. If the
copy fits the L3 cache, the subsequent calculation of std()
can use the data from the L3 cache, which is much faster.
This example shows how we should implement per-tile UDFs #310 in
order to reap the benefits of this, in particular for operations
that are limited by memory transfer. std() is such an operation.
> Example for performance effect of tiling numpy operations

- prototypes/sparse-comparison/performance-recompilation.ipynb
- setup.py
- src/libertem/analysis/com.py
- src/libertem/analysis/disk.py
- src/libertem/analysis/masks.py
- src/libertem/analysis/point.py
- src/libertem/analysis/ring.py
- src/libertem/api.py
- src/libertem/job/masks.py
- src/libertem/masks.py
- src/libertem/preload.py
- tests/test_analysis_com.py
- tests/test_analysis_masks.py
- tests/test_analysis_shapes.py
- tests/test_mask_container.py
See #197 for discussion.
The test in the notebook confirms the advantage even if we first generate dense masks and then convert to sparse.
> Use sparse.pydata.org

- src/libertem/common/buffers.py
- tests/udf/test_simple_udf.py
Added extra_shape parameter for kind="single" buffer so that users can arbitrarily set the dimension of the buffer beyond 1 dimension.
> add extra_shape param to single type buffer

- packaging/creators.json
- src/libertem/web/base.py
- src/libertem/web/cli.py
- src/libertem/web/connect.py
- src/libertem/web/server.py
This fix allows the user to set --local_directory to a folder outside the container.
This then allows Dask to write files for a container deployment.
e.g.
libertem-server --local_directory=$home/dask-user-space
> Issue 80 - Fix to allow container deployment

- prototypes/sparse-comparison/sparse-comparison.ipynb
- setup.py
- src/libertem/analysis/com.py
- src/libertem/analysis/disk.py
- src/libertem/analysis/gridmatching.py
- src/libertem/analysis/masks.py
- src/libertem/analysis/point.py
- src/libertem/analysis/ring.py
- src/libertem/api.py
- src/libertem/job/masks.py
- src/libertem/masks.py
- src/libertem/utils.py
- tests/test_analysis_masks.py
- tests/test_mask_container.py
- tests/test_masks.py
- tests/udf/test_blobfinder.py
- tests/utils.py
Tools and automatisms to control the dtype in which data is read and calculations are performed. All dtype combinations that support numpy.dot() should work now, including integer and complex number types for masks and/or data.
Closes #227 by allow switching to float64 or complex128.
Keep sparse.pydata.org for most of the sparse mask handling, but switch back to scipy.sparse for processing with the correct data layout, which is faster.
Drive-by change: Additional mask generation code and moving utility functions around.
> dtype support

- src/libertem/analysis/com.py
- src/libertem/analysis/disk.py
- src/libertem/analysis/point.py
- src/libertem/analysis/ring.py
- src/libertem/io/dataset/empad.py
- src/libertem/masks.py
- tests/test_analysis_com.py
- tests/test_analysis_shapes.py
1. Fix integer overflow in EMPAD reader
2. Switching the sparse matrix back-end has degraded performance for shallow mask stacks, like for example for the various shape analyses. Since sparse matrices are critical for deep mask stacks where the tests showed good performance (to be checked again, perhaps), disable sparse matrices for the default analyses for now and rely on dense matrices that show good, predictable performance in this scenario.
> Fix EMPAD bug; resolve performance regression

- src/libertem/analysis/base.py
- src/libertem/analysis/radialfourier.py
- src/libertem/api.py
- src/libertem/masks.py
* Optionally include raw results with analysis
* Corrected and improved back-end selection, closes #361 
* Allow overriding the sparse back-end
* More control over radial_bins() to generate it in the desired format right from the start and avoid conversions
* Visualization and AnalysisResult list optionally lazy to avoid unnecessary overheads when using RadialFourierAnalysis within a script. The savings are very significant in some cases and remove a bottleneck in the head node.
* Add visualization of dominant order, display as default
> Streamline code around RadialFourierAnalysis

- src/libertem/web/jobs.py
Sending the messages at the end of the loop can block because of network backpressure if the connection between client and server is slow or unreliable.
Previously, this could severely stall the loop because it would enforce an update for each calculation result, acerbating the problem.
With this change, the delay from sending messages is not counted for the debouncing, which allows the server to process a larger number of results until sending the next message over the network. Additionally, this skips a lot of visualization steps in combination with the lazy calculation implemented in PR #362.
Implement the same logic for UDFs.
Thx @sk1p for the help! :-)
> Ameliorate the effect of network backpressure

- src/libertem/web/jobs.py
Adapt the integration window for results to match the postprocessing and communication time.
This strongly reduces the update rate and increases the integration window if the network creates
backpressure or if calculating the result images is slow. That improves the overall performance and
user experience. We are not getting the results to the GUI anyway -- at least the merging is not
stalled and the next update will show more data when it finally comes.
> Adaptive rate for GUI update

- src/libertem/analysis/fullmatch.py
- src/libertem/analysis/gridmatching.py
- tests/test_gridmatching.py
* Prefer short, orthogonal vectors of equal size -- introduce figure of merit for matches. This leads to more "reasonable", predictable and uniform matches that depend less on the positions in the point cloud.
* Refactoring to make importlib.reload() easier to use
* Uniform behavior of tolerance: always in px, since the limits are hardly used in practice.
> Improvements of gridmatching

- appveyor.yml
- docs/source/app/strain.rst
- docs/source/contributing.rst
- docs/source/reference.rst
- docs/source/udf.rst
- src/libertem/analysis/fullmatch.py
- src/libertem/api.py
- src/libertem/common/buffers.py
- src/libertem/job/masks.py
- src/libertem/udf/__init__.py
- src/libertem/udf/auto.py
- src/libertem/udf/base.py
- src/libertem/udf/blobfinder.py
- src/libertem/udf/logsum.py
- tests/udf/test_auto.py
- tox.ini
That can wrap a function that accepts a frame as a single argument. Together with functools.partial, this allows for a lot of flexibility.
> Auto UDF to allow trivial UDFs without boilerplate

- appveyor.yml
- docs/source/reference.rst
- docs/source/udf.rst
- docs/source/usage.rst
- examples/dask_array.py
- src/libertem/contrib/dask.py
- src/libertem/io/dataset/base.py
- src/libertem/io/dataset/k2is.py
- src/libertem/udf/base.py
- tests/io/test_dask_array.py
- tests/udf/test_by_partition.py
Both are based on creating a tile that covers an entire partition.
FIXMEs:
* Documentation
* Tests for each supported file type -- may require special measures as encountered in K2IS support
Based on PR #377, mostly for practical testing through the new Context.map() function.
Closes #376
See also #286
> Create dask arrays from LiberTEM DataSet; UDF process_partition. Based on PR #377

- docs/source/reference.rst
- src/libertem/masks.py
- src/libertem/udf/blobfinder.py
- tests/test_masks.py
- tests/udf/test_blobfinder.py
Include utility functions to generate advanced templates
The combination of background subtraction, radial gradient, antialiased border and elliptical distortion to match the CBED disk as closely as possible gives outstanding results with CBED strain maps at higher convergence angles recorded with fine detector resolution.
Fix a typo in function name. This might break examples or downstream code, should be included in release 0.2.
Closes #392
> Custom templates for blobfinder

- .travis.yml
- MANIFEST.in
- packaging/appimage/make_app_image.sh
- scripts/release
- scripts/zenodo_upload
- setup.cfg
Before, the release script only handled bumping the version (incl. optionally committing and tagging). 
Now, it also handles:
+ Creating a release on github (via PyGithub)
+ Triggering the wheel/sdist/AppImage build depending on version tags
+ Updating the deposition on zenodo (calls the existing script for now)
+ Uploading release artifacts on github
As the behavior is different for different contexts (branch vs. PR vs. master), I'm putting this up as a PR. In the travis build, wheel/sdist/appimage should be built, but not uploaded anywhere. After merging, the continuous build should be updated and include current wheel/sdist/appimage.
Edit: looks good, continuous release is as it was before.
Still TODO:
> Release script updates

- scripts/zenodo_upload
The Zenodo upload caused a row of spurious internal server errors,
see https://github.com/zenodo/zenodo/issues/1833
The new option lets the scrip return with a success status
after an error to continue with the release CI pipeline.
The Zenodo upload can be performed manually in that case, rather than
failing the entire release script.
> Option to mask Zenodo error

- src/libertem/io/dataset/hdf5.py
- tests/io/test_hdf5.py
TODO better error handling. Right now, the opening dialogue defaults to RAW
if the timeout is triggered.
TODO There seems to be code duplication. between _get_datasets() and detect_params().
@sk1p is there a specific reason to do it like that? I have to admit that I don't fully
understand the consequences of changing this.
TODO: Choose a well-balanced timeout value in case traversing a legitimate file
takes longer than that, for example over network.
Closes #440
> Trigger a timeout when guessing parameters for HDF5 takes too long

- setup.py
Apparently, a merge undid parts of PR #406. This adds the missing change again.
> Remove NumPy pin again

- docs/source/changelog.rst
- docs/source/changelog/bugfix/errorhandling.rst
- docs/source/changelog/documentation/changemanagement.rst
- docs/source/changelog/documentation/checklist.rst
- docs/source/changelog/documentation/clusteringanalysis.rst
- docs/source/changelog/documentation/profiling.rst
- docs/source/changelog/features/clusteringanalysis.rst
- docs/source/changelog/misc/testperformance.rst
- docs/source/contributing.rst
- docs/source/releasing.rst
This helps to avoid merge conflicts and keeps changes nicely separated.
For now, manual merging should do fine. As soon as it becomes annoying we can automate it.
> Use folder structure for changelog of continuous release

- setup.py
Extract bugfix from #460 to crystallize PR
Make sure that a :cite:`...` block at the beginning of a line doesn't create an indentation
when it is removed.
> Fix indentation issue in PyPI description

- src/libertem/udf/blobfinder.py
Giving peak positions as floats is a common mistake and annoyance because
the wrong type leads to an opaque error message downstream. Converting
automatically to int gives the expected result and I can't imagine a scenario
where it wouldn't work.
Crystallizing PR #458
> Round peak positions and convert to int

- setup.py
pypiwin32 is deprecated
This might affect some recent CI failures
> Switch to current pywin32 package

- tests/udf/test_blobfinder.py
Reduce radius to increase clearance between peaks. This fixes occasional issues in CI.
Note: This tries all correlation patterns, that means including the ones that are not so good
at separating close disks.
> Reduce likelyhood of jumps to wrong position

- setup.py
I left in a `!=226` constraint to prevent accidental installation of this known-broken version.
> pywin32 venv installation bug was fixed upstream, relax pinning

- conftest.py
- docs/source/changelog/bugfix/overflow.rst
- src/libertem/io/dataset/raw.py
- tests/io/test_raw.py
Include efficient test case for large file using a sparse file
TODO confirm sparsity on Linux
Fixes #493
> Calculate size as int64 to avoid overflows

- src/libertem/io/dataset/hdf5.py
- tests/io/test_hdf5.py
Patching only the local `current_time` alias of `time.time` should not interfere with other threads.
> HDF5 tests: create alias of time.time for mocking

- .travis.yml
- setup.cfg
- tests/io/test_k2is_uint12.py
- tests/udf/test_blobfinder.py
- tox.ini
This is done by marking tests that exercise jitted functions with
the marker `with_numba`, which are then run again with `NUMBA_DISABLE_JIT=1` as a separate job in the tests stage.
Note that some numba functions are not supported in Python-mode, notably
`to_fixed_tuple`, so we can't get coverage for those functions (yet).
Fixes #474.
> Record coverage for numba njit functions

- .codeclimate.yml
* Increase number of lines per file allowed to 400. This should allow
us to keep things together that belong together, and not force
the reader to jump around multiple files to understand some part of
LiberTEM.
* Increase number of return statements allowed - redux reducers are an
example of code that needs needs to be structured like this - for
example, not having a return statement for each case in the reducer
means we have to watch out for fall-through into the next case etc.
Refs #541
> Configure codeclimate maintainability rules

- src/libertem/io/dataset/cluster.py
- src/libertem/io/dataset/dm.py
- tests/io/test_blo.py
- tests/io/test_cluster_ds.py
- tests/io/test_dm.py
- tests/io/test_empad.py
- tests/io/test_k2is.py
- tests/io/test_mib.py
This adds tests for the NFS-ish use-case for non-natively-distributed formats, and also some tests for the `ClusterDataSet`.
The following formats now have such test cases: DM, K2IS, EMPAD, RAW, MIB.
Most of these don't run in CI yet though, because of missing test data and infra (#86).
This already caught a bug in the DM reader regarding dataset size calculation :grin:
> More tests for distributed use case

- docs/source/changelog/bugfix/blobfinder.rst
- docs/source/changelog/bugfix/fix_pick_roi_interaction.rst
- docs/source/changelog/bugfix/frms6_dist.rst
- docs/source/changelog/bugfix/run_each_host_nonpure.rst
- docs/source/changelog/features/dismiss_err_via_keys.rst
- docs/source/changelog/features/fix_pick_roi_interaction.rst
- docs/source/changelog/obsolescence/remove_hdfs.rst
- src/libertem/udf/blobfinder/correlation.py
- src/libertem/utils/generate.py
- tests/udf/test_blobfinder.py
* Allow running blobfinder tests with NUMBA_JIT_DISABLED
* Fixes and test cases for the bugs that were uncovered in the process
* Managing changelog entries as a minor drive-by change
@sk1p it was really worth working on the NUMBA_JIT_DISABLED test capability.  Numba doesn't do bounds checks just as C, and testing with JIT disabled catches bugs that access the wrong memory.
> Blobfinder fixes; changelog update

- tests/test_analysis_masks.py
Fix potential mismatch from performing calculations with different dtypes, refs #556
> Use the same dtype as _naive_mask_apply

- src/libertem/udf/blobfinder/correlation.py
This allows users to get the correlation pattern for debugging and
visualization purposes.
I was missing this function when working on the bullseye example
> Peak finding correlation pattern in separate function

- conftest.py
- docs/source/changelog/features/hdf5_tileshape_optional.rst
- src/libertem/io/dataset/hdf5.py
- tests/io/test_hdf5.py
- tox.ini
> HFD5: make tileshape optional

- docs/source/api.rst
- docs/source/app/holography.rst
- docs/source/architecture.rst
- docs/source/changelog.rst
- docs/source/changelog/misc/distributed.rst
- docs/source/changelog/obsolescence/jobremoval.rst
- docs/source/formats.rst
- docs/source/reference/api.rst
- docs/source/tips.rst
- setup.py
- src/libertem/analysis/base.py
- src/libertem/analysis/masks.py
- src/libertem/analysis/raw.py
- src/libertem/analysis/rawfft.py
- src/libertem/api.py
- src/libertem/io/dataset/memory.py
- src/libertem/job/base.py
- src/libertem/job/masks.py
- src/libertem/job/raw.py
- src/libertem/udf/FEM.py
- src/libertem/udf/base.py
- src/libertem/udf/blobfinder/utils.py
- src/libertem/udf/crystallinity.py
- src/libertem/udf/feature_vector_maker.py
- src/libertem/udf/holography.py
- src/libertem/udf/stddev.py
- src/libertem/web/connect.py
- test_requirements.txt
- tests/test_analysis_rawfft.py
- tests/test_job_deprecation.py
* Update documentation and docstrings
* Move Task from Job to UDF code base
* Fix RawFFT that was broken from making UDF the default back-end
* Improve RawFFT tests to catch such issues in the future
* Drive-by change: Dask to >=2.2.0 and fix of parameter name
> Update documentation for Job deprecation

- scripts/release
- scripts/zenodo_upload
First part of #431. Next part will need some restructuring of the release script, switching the ordering of GitHub release and Zenodo upload.
> zenodo_upload: support for uploading more than two files

- .travis.yml
- docs/source/releasing.rst
- scripts/release
- scripts/requirements.txt
Download repo snapshot from `/archive/{tag}.tar.gz`, upload that to zenodo and move zenodo upload after GitHub release creation. Fixes #431.
> Upload release repo snapshot to zenodo

- docs/source/changelog/features/open_browser.rst
- docs/source/usage.rst
- packaging/creators.json
- src/libertem/web/cli.py
- src/libertem/web/server.py
Open browser after starting the server.
cli has a new flag --no-browser , if present
the browser will not open.
> Fix issue 81

- scripts/release
> Make it harder to misuse the `bump` command

- docs/source/changelog/bugfix/hdf5_roi_fix.rst
- docs/source/changelog/misc/removeme.rst
- docs/source/udf/profiling.rst
- src/libertem/io/dataset/hdf5.py
- tests/io/test_hdf5.py
The `roi` needs to be flat when calculating the frame offset.
> HDF5: fix tile offset if reading with roi

- docs/source/changelog/bugfix/hdf5_full_frame_auto_tileshape.rst
- src/libertem/io/dataset/hdf5.py
- tests/io/test_hdf5.py
- tests/utils.py
> HDF5: Fix crash w/ full_frame + no tileshape param

- docs/source/changelog/features/get_extensions.rst
- src/libertem/io/dataset/__init__.py
- src/libertem/io/dataset/base.py
- src/libertem/io/dataset/blo.py
- src/libertem/io/dataset/dm.py
- src/libertem/io/dataset/empad.py
- src/libertem/io/dataset/frms6.py
- src/libertem/io/dataset/hdf5.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- src/libertem/io/dataset/ser.py
- tests/io/test_base.py
Returns a set of supported file extensions for all datasets
> Add `get_extensions` function to `libertem.io.dataset`

- docs/source/changelog/bugfix/hdf5_full_frame_auto_tileshape.rst
- docs/source/changelog/bugfix/hdf5_roi_fix.rst
- docs/source/changelog/features/get_extensions.rst
* Remove items that were released as part of v0.4.1
* Fix typo/syntax error in headline of get_extensions.rst
> Cleanup for changelog items

- docs/source/changelog/features/filetype_auto.rst
- docs/source/formats.rst
- src/libertem/api.py
- src/libertem/io/dataset/__init__.py
- src/libertem/io/dataset/hdf5.py
- tests/io/test_base.py
This adds a new method `dataset_info` to our `Context` class, which detects the dataset type and returns some information about it (same as is available via the web GUI). This is for example useful if you are opening an HDF5 file and don't know which `ds_path` to choose.
Would love to get some feedback on this!
Also contains a little fix to sort HDF5 data sets in the diagnostics by size, as that is often the most useful when trying to decide what `ds_path` to open.
If this is useful, I'll add ~tests~, documentation and changelog entry!
Closes: #616
> Add `filetype=auto` to `Context.load`

- src/libertem/common/buffers.py
- src/libertem/udf/base.py
Use case: initialization to enable simplifications of the merge
function, in case of a non-zero "neutral element."
Also clean up code duplication between `run_for_dataset{,_async}`
@uellue does this fix your issue?
> RFC: call preprocess on master node, too

- docs/source/changelog/features/preprocess.rst
- docs/source/changelog/features/stddev.rst
- docs/source/udf/advanced.rst
- src/libertem/analysis/clust.py
- src/libertem/udf/stddev.py
- tests/udf/test_stddev.py
* Documentation and changelog for #624
* More than 2x speed-up of StdDevUDF  in tests
The computation can likely be accelerated further with a cache-optimized Numba implementation of combined variance and sum:
```
Timer unit: 1e-07 s
Total time: 0.397086 s
File: c:\users\weber\documents\libertem\libertem\src\libertem\udf\stddev.py
Function: merge at line 11
Line #      Hits         Time  Per Hit   % Time  Line Contents
==============================================================
11                                           def merge(p0, p1):
12                                               """
13                                               Given two sets of partitions, with sum of frames
14                                               and sum of variances, compute joint sum of frames …
```
> Tiled StdDevUDF

- docs/source/changelog/misc/raw_perf_large_tiles.rst
- src/libertem/io/dataset/base.py
- src/libertem/io/dataset/raw.py
- tests/io/test_raw.py
Allocating large buffers with zeros_aligned is slower
than using np.zeros, but is still needed for direct I/O.
This change only enables `zeros_aligned` for direct I/O and also
implements a shortcut in `_get_tiles_with_roi` if the roi is all-zeros
> Fix performance issue w/ large tiles

- docs/source/app/amorphous.rst
- docs/source/changelog/features/stddev.rst
- docs/source/changelog/misc/stddev.rst
- docs/source/citing.rst
- docs/source/reference/udf.rst
- docs/source/references-libertem.bib
- docs/source/udf.rst
- setup.py
- src/libertem/analysis/sd.py
- src/libertem/udf/stddev.py
- tests/udf/test_make_feature_vec.py
- tests/udf/test_stddev.py
This version is ~~slightly~~ about 2x faster compared to the version in #625 for the benign case of signal buffers that fit comfortably into the CPU caches.
For the malign case of signal buffers that don't fit the caches well,
it is about 10x faster since it eliminates large intermediate buffers and
calculates ~~each pixel in one pass~~ the result in cache-friendly blocks and CPU -friendly access patterns.
* Added test for numerical stability.
* Added citation in bibtex
> Numba-based StdDevUDF

- docs/source/changelog/bugfix/raw_direct_io_windows.rst
- src/libertem/io/dataset/raw.py
- tests/io/test_raw.py
Fixes #658 
An exception is raised when Direct I/O is enabled for raw files on Windows and a user-friendly error message is shown on the GUI.
> Exception for Direct I/O for raw files on Windows

- override_requirements.txt
Needs to stay this way as long as the rest of the file is empty,
otherwise all dependencies are installed via those indexes under
some circumstances.
> Comment out index URLs from override_requirements

- docs/source/changelog/misc/threading.rst
- docs/source/gsoc.rst
- examples/basic.py
- examples/center_of_mass.ipynb
- examples/digital-micrograph-basic.py
- examples/pcmclustering.ipynb
- examples/peak_selector.ipynb
- examples/radialfourier.ipynb
- examples/simple libertem API.ipynb
- prototypes/set-threadcount.ipynb
- setup.py
- src/libertem/udf/base.py
- src/libertem/utils/threading.py
Having to set the thread count through environment variables can be problematic in some situations #546 and is an error source with severe performance penalties from over-subscription on machines with many cores #602.
In this PR I am planning to include support for setting the thread count to 1 on the workers, i.e. not having to set environment variables anymore. Allowing multi-threaded UDFs should likely be implemented in a follow-up PR later.
With this feature in mind, I am already setting the thread count in `run_for_partition()`.
Getting the previous number of threads is not always reliable, as it turns out. For that reason I am just setting the number and not trying to restore it after.
> Set thread count dynamically for each UDF run

- prototypes/reproducers/test-dask-remote.ipynb
- setup.py
The notebook prototypes/reproducers/test-dask-remote.ipynb
reliably locked up or errored when using it with a remote dask
cluster of version 2.9.0 or newer.
Tested on moellenstedt in a new clean conda environment with LiberTEM
master, Python 3.7.
@sk1p could you perhaps test if you can reproduce it locally on your machine? I couldn't reproduce it on my Windows machine.
> Limit to distributed < 2.9

- .travis.yml
- src/libertem/io/dataset/raw.py
- tests/executor/test_dask.py
- tests/io/test_raw.py
- tests/test_analysis_radialfourier.py
- tests/udf/test_make_feature_vec.py
See also: #679
TODO:
Radial fourier, both for `JOB` and `UDF`:
```
>       assert np.allclose(np.angle(c_1_2[1, 0]), np.pi)
E       assert False
E        +  where False = <function allclose at 0x10e45d6a8>(-3.141592653589793, 3.141592653589793)
E        +    where <function allclose at 0x10e45d6a8> = np.allclose
E        +    and   -3.141592653589793 = <function angle at 0x10e58dd90>((-0.981522951893353-9.77719708014513e-19j))
E        +      where <function angle at 0x10e58dd90> = np.angle
E        +    and   3.141592653589793 = np.pi
```
Feature vector: 
```
>       assert np.all(result['feature_vec'].data[0:3, 0:2])
E       assert False
E        +  where False = <function all at 0x10e445510>(array([[ True, False],\n       [ True, False],\n       [ True, False]]))
E        +    where …
```
> Add OS X tests

- docs/source/udf.rst
- setup.py
- src/libertem/common/buffers.py
- src/libertem/udf/base.py
- tests/udf/test_simple_udf.py
The default merge function throws a NotImplementedError when used
for kinds other than 'nav'
> Limit default merge to kind='nav' buffers

- test_requirements.txt
Works around bug in latest version (https://github.com/pytest-dev/pytest-asyncio/issues/154)
```_____________________ test_start_server __________________________________________________________________
base_url = 'http://127.0.0.1:45153', http_client = <aiohttp.client.ClientSession object at 0x7f2cfedb1e90>
@pytest.mark.asyncio
async def test_start_server(base_url, http_client):
"""
start the server and HTTP GET '/', which should
return a 200 status code
"""
url = base_url
>       async with http_client.get(url) as response:
tests/server/test_startup.py:36:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.tox/py37/lib/python3.7/site-packages/aiohttp/client.py:1012: in __aenter__
self._resp = await self._coro …
```
> Pin pytest-asyncio to <0.11

- src/libertem/common/buffers.py
* Use `Slice` objects as keys, which are hashable
* Assert that they don't overlap
* Make sure we only flush correctly and trigger an error otherwise
We only have to check once when a new key is created for the cache,
which means it shouldn't noticeably impact performance. Plus, we can
deactivate asserts for production.
> Detect discrepancies in `Buffer` cache use

- docs/source/changelog/misc/cli_alias.rst
- docs/source/usage.rst
- src/libertem/web/cli.py
cmd line options can be accessed with shorter alternatives
> Add alias to cmd line options

- tests/corrections/test_detector.py
Otherwise it heavily accumulates numerical errors.
For that reason, make the distribution asymmetric around zero.
Closes #761
> Make sure the sum of the mask is not close to zero

- src/libertem/io/dataset/seq.py
- tests/io/datasets/test_seq.py
Exception for the following error which can be reproduced by loading a raw file:
`UnicodeDecodeError: 'utf-16-le' codec can't decode bytes in position 452-453: il
legal encoding`
> SEQ: UnicodeDecodeError exception

- conftest.py
- tests/io/datasets/test_seq.py
> The way _mk_random currently generates test data means we get only the values from the set {0.0, 1.0, 288.0, 2880.0} for default_raw. The binary representation of those float values all start with a '\x00' - so the first string value, which is at offset 4, will always be truncated to zero length and trigger the error. If we do change the function to generate values that have a larger fractional value in the binary representation (which we might want to do!), this assumption will no longer hold.
Thanks for the explanation :)
> Better test to trigger UnicodeDecodeError

- docs/source/changelog/features/multi_udf_runner.rst
- src/libertem/analysis/clust.py
- src/libertem/api.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/udf/base.py
- src/libertem/web/jobs.py
- tests/io/test_tiling_negotiation.py
- tests/udf/test_multi_udf.py
- tests/udf/test_udf_runner.py
This is most important for processing live data where you can't do multiple passes over a data set. This is not yet exposed via the public APIs, it is currently available via the `UDFRunner`.
> Support for running multiple UDFs simultaneously 

- tests/conftest.py
- tests/server/test_browse.py
- tests/server/test_cancel.py
- tests/server/test_dataset.py
- tests/server/test_download.py
- tests/server/test_ds_detect.py
- tests/server/test_job.py
- tests/server/test_startup.py
- tests/server/test_state.py
This is needed to properly isolate event loops, and allows to test edge cases, for example shutting down the server.
> Run LiberTEM test server in a separate event loop

- docs/source/changelog/features/com.rst
- docs/source/changelog/features/coordinates.rst
- docs/source/concepts.rst
- src/libertem/analysis/com.py
- src/libertem/api.py
- src/libertem/corrections/coordinates.py
- src/libertem/masks.py
- src/libertem/utils/__init__.py
- tests/corrections/test_coordinates.py
- tests/test_analysis_com.py
- tests/test_utils.py
Replaces #789 as a clean version
* Support flipping y axis (MIB) and adjusting scan rotation in COM analysis. Refs #325 #121
* Set of validated functions to do transformations, for consistent use within LiberTEM
* Additional description in concepts.rst
* Allow center outside of field of view for radial_bins
> Coordinate transform support for COM Analysis

- docs/source/usage.rst
- src/libertem/executor/dask.py
- tests/test_local_cluster.py
Makes it easier to integrate LiberTEM in existing clusters
Limits execution to CPU only
CC @jhgee probably relevant for easily running in ipyparallel through https://ipyparallel.readthedocs.io/en/latest/api/ipyparallel.html#ipyparallel.Client.become_distributed
> Allow running on a vanilla Dask cluster like before

- src/libertem/io/dataset/mib.py
- tests/io/datasets/test_mib.py
> Add a warning if a MIB data set is saved in an inefficient way

- benchmarks/corrections/test_corrset.py
- benchmarks/test_smoke.py
- docs/source/changelog/features/corrections.rst
- setup.py
- src/libertem/analysis/com.py
- src/libertem/corrections/corrset.py
- src/libertem/corrections/detector.py
- src/libertem/io/dataset/base/backend.py
- src/libertem/io/dataset/base/partition.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/io/dataset/memory.py
- src/libertem/io/dataset/ser.py
- src/libertem/udf/base.py
- tests/corrections/test_corrset.py
- tests/corrections/test_detector.py
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_cluster_ds.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_empad.py
- tests/io/datasets/test_frms6.py
- tests/io/datasets/test_hdf5.py
- tests/io/datasets/test_k2is.py
- tests/io/datasets/test_mem.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_raw.py
- tests/io/datasets/test_seq.py
- tests/io/datasets/test_ser.py
- tests/io/test_tiling_negotiation.py
- tests/utils.py
Closes #818 
Correction only makes sense for floating point data.
* Inplace: Throws TypeError for non-float data
* Copy: Cast to matching floating point type.
@sk1p How is it handled in the dataset corrections code? Do we make sure it is float when correction is turned on?
> Make sure correction handles integer input data correctly

- src/libertem/common/buffers.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/io/dataset/blo.py
- src/libertem/io/dataset/dm.py
- src/libertem/io/dataset/empad.py
- src/libertem/io/dataset/frms6.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- src/libertem/io/dataset/raw.py
- src/libertem/io/utils.py
- src/libertem/udf/raw.py
- tests/io/datasets/test_k2is.py
Added `dtype=np.int64` to `np.prod` to fix the `RuntimeWarning: overflow encountered in long_scalars` error while negotiating a tiling scheme.
> Overflow fix for np.prod

- benchmarks/corrections/test_corrset.py
`sig_shape` was `(1014, 1024)` and coordinates were outside of this. Seems like this was previously ignored silently, but is now failing.
Fixes #868
> Fix typo in shape used in corrset benchmark

- src/libertem/masks.py
- tests/test_masks.py
Fix for empty rectangular ROI in the GUI throwing `UnboundLocalError: local variable 'ymin' referenced before assignment`
> Handle empty rect ROI

- src/libertem/io/dataset/empad.py
- tests/io/datasets/test_empad.py
The lazy way of using `pix_x`, `pix_y` doesn't work anymore with current EMPAD files, so do the sensible thing and read from `scan_parameters > scan_resolution_y`
> More robust support for EMPAD acquisitions

- docs/source/changelog/features/dm-stacks-of-3d.rst
- src/libertem/io/dataset/dm.py
Before, we only supported loading stacks of 2D images, where each image
was in its own file. This adds support for the case where there is more
than one 2D image per file, stacking the images along the Z axis.
@AnandBaburajan I plan to merge this PR (and possibly also #873) before your GSoC PR is merged, would that be OK? It will probably result in a small conflict, that should be easy enough to resolve.
/cc @FENGSHAN95
> Support for loading stacks of 3D DM files

- src/libertem/analysis/apply_fft_mask.py
- src/libertem/analysis/base.py
- src/libertem/analysis/clust.py
- src/libertem/analysis/com.py
- src/libertem/analysis/fem.py
- src/libertem/analysis/masks.py
- src/libertem/analysis/radialfourier.py
- src/libertem/analysis/raw.py
- src/libertem/analysis/sd.py
- src/libertem/analysis/sum.py
- src/libertem/analysis/sumfft.py
- src/libertem/analysis/sumsig.py
- src/libertem/common/container.py
- src/libertem/executor/dask.py
- src/libertem/job/masks.py
- src/libertem/udf/base.py
- src/libertem/udf/masks.py
- src/libertem/utils/threading.py
Mostly this prevents importing pytorch, matplotlib, skimage, sklearn at
import time. Local/lazy imports should still perform well (some ns), as they
reduce to something like a dict lookup.
This improves initial import time, measured as
python -c 'import libertem.api'
by a factor of two. Running some of our slowest tests (tests/executor
and tests/server) is reduced from 264s to about 220s on my workstation. Let's see how the
CI time is improved, hopefully there the impact is even larger.
Something like the following was used to profile import times:
```
PYTHONPROFILEIMPORTTIME=1 python -c 'import libertem.api' 2>&1 | sort -k 3 -n
```
@uellue thoughts?
> Lazily import some dependencies

- src/libertem/analysis/radialfourier.py
- tests/template/test_radial_fourier_template.py
Dominant order produces different output, might
be triggered by many cores/ many workers.
Thx @sk1p @uellue
Fixes #895 
> Fix radial fourier template test

- docs/source/changelog/bugfix/aux_failure_single_frame_part.rst
- src/libertem/common/buffers.py
- tests/udf/test_aux_data.py
If a partition consists of a single "sig" item, aux data shapes don't match. The singular dimension is "swallowed" somehow, apparently. I tried to find out where, but didn't get far.
This is mostly an issue for testing since normally partitions contain more than one sig element. For memory partitions, the "num_partitions" parameter can be set in such a way that no partitions with singular nav shape are created as a work-around.
Fixes #791
> Fix AUX data failure with single frame partitions

- .github/PULL_REQUEST_TEMPLATE
- docs/source/changelog/bugfix/add_shape_to_tuple.rst
- docs/source/changelog/bugfix/corrections.rst
- docs/source/changelog/bugfix/diasble_quickedit()
- docs/source/changelog/bugfix/disable_quickedit_win.rst
- docs/source/changelog/bugfix/no-copy-multi-file.rst
- src/libertem/io/dataset/base/backend.py
- src/libertem/io/dataset/dm.py
- tests/io/datasets/test_dm.py
Zero-copy reading was not well tested with multiple files, resulting in #904. Also, the DM reader didn't properly calculate the `start_idx` and `end_idx` with multiple files with more than one frame per file (#903).
Fixes #903, fixes #904
> Fix problems with zero-copy reading and DM

- .gitignore
- azure-pipelines-data.yml
- azure-pipelines.yml
- docs/source/contributing.rst
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_ser.py
Fixes #86. The test data is provided as a bind mount at `/data/` (currently pointing to a directory owned by my user, where I put the private test data to mirror my local setup, but that can be changed).
> Add pipeline with data access

- conftest.py
- src/libertem/api.py
- src/libertem/executor/dask.py
- tests/test_analysis_masks.py
- tests/test_context.py
- tests/test_local_cluster.py
Give a meaningful error message if a bad value is passed as an executor.
Refs #918 
Drive-by change: Fix tests to not lock up when I run them on moellenstedt with remote VSCode. Not sure if the lock-ups occur under other circumstances as well.
> Check parameter `executor` in api.Context; fix tests

- docs/source/bibtex.json
- docs/source/conf.py
- docs_requirements.txt
- tox.ini
This is required because of some backward-imcompatibilities, namely the requirement for setting `bibtex_bibfiles`. Include the `bibtex.json` file in source control as suggested by upstream, if this is kept up to date this means we could remove the second build pass for updating the references.
Also:
- use parallel building to speed up the build.
- extract requirements for building docs into its own requirements file, which can be shared between tox environments
> Update configuration for new sphinxcontrib-bibtex release

- conftest.py
- docs/source/changelog/bugfix/multiple_dask_clients.rst
- docs/source/install.rst
- docs/source/tips.rst
- src/libertem/executor/dask.py
- src/libertem/udf/base.py
- tests/corrections/test_corrset.py
- tests/executor/test_dask.py
- tests/io/test_cached.py
- tests/test_local_cluster.py
- tox.ini
This is needed if there are multiple distributed `Client`s running in the same process, as the `Client` that was created last is registered as the global `Client` and then used for functions like `dd.as_completed`. That means we create futures on a different loop than we try to retrieve their results, which results in hangs (can be debugged using `PYTHONASYNCIODEBUG=1`), as setting the result for a future is not threadsafe.
As a drive-by fix, workers are now started in parallel in `libertem-worker`.
Refs #919 #684 #482
> Use the right loop in dd.as_completed

- docs/source/changelog/features/cache-warmup.rst
- src/libertem/corrections/detector.py
- src/libertem/executor/base.py
- src/libertem/executor/dask.py
- src/libertem/executor/inline.py
- src/libertem/io/dataset/base/backend.py
- src/libertem/io/dataset/base/decode.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/udf/holography.py
- src/libertem/udf/stddev.py
- src/libertem/web/dataset.py
- tests/executor/test_dask.py
- tests/executor/test_inline.py
- tests/server/test_dataset.py
- tests/udf/test_holography.py
Fixes #798 once numba properly caches functions with w/ closures over other functions. Independent from this, we can decide if we want to add a work-around to make these functions cacheable. 
> JIT caching updates

- docs/source/changelog/features/linlogscale.rst
- prototypes/reproducers/create-outlier-data.ipynb
- src/libertem/analysis/base.py
- src/libertem/analysis/com.py
- src/libertem/analysis/masks.py
- src/libertem/analysis/raw.py
- src/libertem/analysis/sd.py
- src/libertem/analysis/sum.py
- src/libertem/api.py
- src/libertem/common/buffers.py
- tests/test_analysis_raw.py
- tests/test_analysis_shapes.py
- tests/test_analysis_sum.py
Closes #925 with a small modification to make sure large outliers
don't generate a completely blank plot.
See https://github.com/LiberTEM/LiberTEM/issues/925#issuecomment-744483882
for more discussions and an idea for a more comprehensive solution
Full implementation would be #134
> Allow choosing between lin and log visualization

- docs/source/changelog/bugfix/autoload.rst
- src/libertem/api.py
- src/libertem/io/dataset/__init__.py
- src/libertem/io/dataset/hdf5.py
- tests/io/datasets/test_backend.py
- tests/io/datasets/test_frms6.py
- tests/io/test_base.py
- tests/utils.py
Closes #936
This change allows to pass arbitrary positional and keyword arguments to
datasets loaded with 'auto' and with a specified type. This is tested with
FRMS6 since it triggered the original bug and has a number of
optional arguments which are convenient for testing.
* Turn `executor` and `enable_async` into keyword-only arguments to avoid
collisions with user-provided positional arguments
* Make sure that *args and **kwargs are passed forward in all cases
* Avoid auto-detected parameters overriding or colliding with user-
provided arguments. That is achieved by ignoring all
detected values except the type
* Consequence: Make sure that dataset initialization can autodetect
all optional or detectable parameters since they will not be passed
to load() anymore. Only `ds_path` for HDF5 …
> Handle user-provided positional and keyword arguments for autoloading

- src/libertem/win_tweaks.py
- tests/test_win_tweaks.py
Show a warning pointing to the probable fix,
disable the affected feature and continue running
instead of failing hard.
Closes #949 
> Handle misconfigured pywin32 gracefully

- conftest.py
- src/libertem/common/shape.py
- src/libertem/io/dataset/hdf5.py
- tests/common/test_shape.py
- tests/io/datasets/test_hdf5.py
Fixes #955. 2D HDF5 files are not yet supported; in LiberTEM it probably only makes sense to open stacks of 2D HDF5 files, if at all.
Also improve `Shape.size`:
* Empty `Shape` objects (i.e. ()) now have a defined size instead of throwing an exception
> Better error message when trying to open 2D HDF5 files

- src/libertem/utils/devices.py
- tests/test_win_tweaks.py
- tests/utils/test_devices.py
This includes the case of missing compute capability support in the installed CUDA runtime. Check moved to `has_cupy`.
Fixes #959
> Catch more broken cupy installations

- docs_requirements.txt
- src/libertem/io/dataset/empad.py
- src/libertem/io/dataset/frms6.py
> File access only through executor

- benchmarks/io/test_hdf5.py
- src/libertem/io/dataset/hdf5.py
Improves cold read performance on my system with chunked HDF5 files, maybe fixes #971 
> HDF5: use chunking as base tileshape

- benchmarks/io/test_mib.py
- prototypes/gridreduction/Gridmaker.ipynb
- src/libertem/analysis/fullmatch.py
- src/libertem/analysis/gridmatching.py
- src/libertem/api.py
- src/libertem/common/buffers.py
- src/libertem/common/numba.py
- src/libertem/executor/base.py
- src/libertem/executor/dask.py
- src/libertem/executor/inline.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/masks.py
- src/libertem/udf/base.py
- src/libertem/utils/generate.py
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_empad.py
- tests/io/datasets/test_frms6.py
- tests/io/datasets/test_hdf5.py
- tests/io/datasets/test_k2is.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_raw.py
- tests/io/datasets/test_seq.py
- tests/io/datasets/test_ser.py
- tests/io/test_tiling_negotiation.py
- tests/test_analysis_sum.py
- tests/udf/test_by_tile.py
- tests/udf/test_simple_udf.py
Previously, the tile shape was always calculated for the full partition size regardless of ROI. That can lead to a relatively large number of very small tiles if the ROI is almost empty in the area of a partition. With this change, the tile shape is calculated based on the actual size that will be processed.
Additional changes:
* Vestigial remnant of the job interface excised
* Handle https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
> Consider ROI size in tiling; drive-by cleanup

- docs/source/changelog/features/threading_control.rst
- src/libertem/executor/base.py
- src/libertem/executor/dask.py
- src/libertem/executor/inline.py
- src/libertem/udf/base.py
- tests/executor/test_dask.py
- tests/executor/test_inline.py
- tests/udf/test_simple_udf.py
The `JobExecutor` is in complete control over the threading, so it can also decide to allow fine-grained Python/C threads in each process, for example if we only start `NUM_OF_CORES/2` processes, or in single-process mode (`InlineJobExecutor`).
This is the minimal change, a complete implementation could add information about the number of threads to `UDFMeta`, as discussed before.
> Move threading control to JobExecutor

- conftest.py
- docs/source/udf.rst
- src/libertem/executor/inline.py
- tests/executor/test_inline.py
- tests/io/datasets/test_hdf5.py
- tests/test_fullmatch.py
* allow limiting the number of threads in the `InlineJobExecutor`
* apply a limit of 2 in the `lt_ctx` fixture. Let's see if this fixes long test runtimes on Windows
* remove some deprecated `np.{float,bool}` usage
> General housekeeping PR

- docs/source/changelog/bugfix/udf-consistency.rst
- docs/source/changelog/features/udf-get-results.rst
- docs/source/udf.rst
- docs/source/udf/advanced.rst
- src/libertem/common/buffers.py
- src/libertem/exceptions.py
- src/libertem/udf/base.py
- src/libertem/udf/logsum.py
- src/libertem/udf/raw.py
- src/libertem/udf/stddev.py
- src/libertem/udf/sum.py
- src/libertem/warnings.py
- tests/udf/test_buffer_declarations.py
- tests/udf/test_by_tile.py
- tests/udf/test_meta.py
- tests/udf/test_simple_udf.py
- tests/utils.py
Now, all accesses to buffers in `UDF.results` and the `src`/`dest` parameters of `UDF.merge` should be done via `__getattr__`; if the `BufferWrapper` is really needed, then `UDF.results.get_buffer` should be used.
As a follow-up to #994, `get_results` now should consistently return numpy arrays, which are then converted to `BufferWrapper`s before returning them to the user. This means we can make `get_results` a bit more DRY by not having to repeat buffer names. Also, buffers that don't have to be post-processed, can be left out in `get_results`, and will be returned unchanged. If you want to use a buffer only internally, without exposing it to the user, pass `use='private'` to `UDF.buffer`.
The `allocate` parameter was merged with the `use` parameter, and now `use='result_only'` should …
> UDF: Consistency fixes and `get_results` improvements

- docs/source/changelog/bugfix/mpl-3-4-issues.rst
- src/libertem/viz.py
Applying a `Norm` to >2D data is no longer allowed, so we reshape
the data appropriately. Also needed an additional fix for all-nan results.
Fixes #1007.
> Fixes for matplotlib 3.4

- src/libertem/analysis/base.py
- src/libertem/api.py
- The example in `AnalysisResultSet` should be displayed as one code snippet, not individual independent examples.
- s/Properties/Attributes/ for `Context.plot_class` - Properties is not recognized by sphinx, so it is taken as part of `Parameters`...
> Some small doc tweaks

- docs/source/changelog/bugfix/com.rst
- src/libertem/analysis/com.py
The compnents were in the wrong order
* [X ] I have added or updated my entry in [the creators.json file](https://github.com/LiberTEM/LiberTEM/blob/master/packaging/creators.json)
> Bugfix for COM analysis template

- conftest.py
- data/temp_data/.placeholder
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_k2is.py
- tests/template/test_ring_template.py
This should allow to run these tests with any Dask scheduler that
is passed via DASK_SCHEDULER_ADDRESS and data via TESTDATA_BASE_PATH.
In particular, make sure that the tests don't write to hardcoded absolute
paths that could accidentally overwrite files on a user's system.
Let's see if it still works in CI!
> Fix hard-coded paths and addresses in some dist tests

- conftest.py
- src/libertem/common/numba.py
- src/libertem/io/dataset/hdf5.py
- src/libertem/web/messageconverter.py
- tests/common/test_numba.py
This fixes cache warmup for HDF5 files, that have different requirements for the tiling scheme depending on roi/non-roi runs.
Also run warmup with both SumUDF and PickUDF
> warmup: run tiling scheme negotiation w/ roi

- client/src/cluster/components/GPUSelector.tsx
Rebuilt client is left out, this can be fixed with some other GUI client
> Left over link fix

- conftest.py
- packaging/docker/Dockerfile
> ipyparallel: use `Client.wait_for_engines(...)`

- conftest.py
- docs/source/changelog/bugfix/glob.rst
- src/libertem/io/dataset/cached.py
- src/libertem/io/dataset/frms6.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- tests/io/datasets/test_frms6.py
- tests/io/datasets/test_k2is.py
- tests/io/datasets/test_mib.py
Closes #1066
* A bit of refactoring to make the code more uniform and easier to test
* Skip only tests that need test data since the glob tests don't need it
> Escape globs to allow special characters in file names

- docs/source/changelog/bugfix/rgb.rst
- src/libertem/viz/base.py
- tests/viz/test_viz_base.py
For example RGB plots for colorwheel visualization for vector fields.
Closes #1052
> Allow extra dimensions for plot data compared to damage

- docs/source/changelog/bugfix/workercount.rst
- src/libertem/executor/scheduler.py
- src/libertem/io/dataset/__init__.py
- tests/test_local_cluster.py
This may be slower than necessary for UDFs that support mixed GPU + CPU processing,
but the penalty is probably less than having a residual partition.
Closes #1086
Thx @matbryan52 for reporting!
> Only count CPU workers

- src/libertem/udf/base.py
- tests/udf/test_by_partition.py
- tests/udf/test_coords.py
The tile can still be overridden by the dataset, it is not guaranteed to
actually be a partition!
Amends #1107 
> Set correct slice info for partition

- docs/source/changelog/bugfix/memleak-fn-caching.rst
- src/libertem/executor/dask.py
The root cause for #894 is (unbounded) caching of functions that are submitted to the dask cluster - we need to make sure we use a consistent function and not directly submit callables that are generated on the fly.
Closes #964, closes #894
> Work around memory leak, fixes #894

- benchmarks/udf/test_simple_udf.py
- docs/source/acknowledgments.rst
- docs/source/changelog/misc/threadcount.rst
- src/libertem/executor/dask.py
- src/libertem/udf/base.py
- src/libertem/utils/threading.py
- src/libertem/utils/threadpoolctl.py
Closes #1117
Resetting the module cache on a distributed executor causes
so much overhead that it negates any benefits. For that reason
this change accepts that the threading settings might
depend on UDF execution order under some circumstances.
> Caching threadpoolctl modules

- docs/source/changelog.rst
- src/libertem/io/dataset/seq.py
to find `.seq.*` with correction data.
Closes #1120
> Support both `.seq` and `.seq.seq` as extension for the main SEQ file

- benchmarks/udf/test_transfer.py
Benchmark to compare parameter and result transfer through the executor
with transfer through the file system as a baseline.
On my system:
Win10, distributed==2021.5.1, cloudpickle==1.6.0, python==3.8.5
* test_param[preshared_file]       189.8526
* test_param[file]                 203.5551
* test_param[executor]           1,123.3426
* test_result[file]           505.6191
* test_result[executor]     1,268.2503
@matbryan52 @sk1p  this can be the baseline for improving this. As you can see, there's lots of potential! :-)
* [N/A] I have included the [rebuilt production build of the …
> Benchmark data transfer

- docs/source/changelog/misc/large-parameters.rst
- setup.py
- src/libertem/executor/base.py
- src/libertem/executor/dask.py
- src/libertem/executor/inline.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/udf/base.py
- tests/udf/test_memleak.py
- tests/udf/test_resources_for_backends.py
- tests/udf/test_simple_udf.py
- tests/udf/test_udf_runner.py
Parameters that are constant for the whole `UDF` run are now handled separately from other task-related data that actually changes for each partition. Executors can implement efficient scattering/broadcasting of parameters now, as implemented here for the `DaskJobExecutor`.
> Refactor UDF parameter handling

- azure-pipelines.yml
See announcement here:
https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/
Mac OS X 10.14 will soon be dropped from Azure Pipelines, and 10.15
seems to be the last image that supports Python 3.6
See toolset definitions here:
https://github.com/actions/virtual-environments/tree/main/images/macos/toolsets
I guess once Python 3.6 is dropped completely, we could either drop
support on Mac OS, or install via miniconda (probably slow...)
* [N/A] I have added/updated documentation for all user-facing …
> Move to Mac OS X 10.15 for Python 3.6 tests

- prototypes/advancedexecutor/minimaldask.ipynb
It emulates the basic steps of LiberTEM UDF: Cut the data in partitions,
calculate results dynamically per partition, assemble on main node.
Different from the current executor, partition and parameters are passed in as
function arguments so the scheduler has more insight and control over that.
CC @sk1p @matbryan52  :-)
> Prototype that uses futures and dask arrays

- src/libertem/viz/bqp.py
- tests/viz/test_bqp.py
- tests/viz/test_gms.py
- tests/viz/test_mpl.py
Extracted from #1025:
- Resilience against empty damage region in plotting
- Allow manipulation of color scales from outside
> bqp updates

- docs/source/changelog/misc/preload.rst
- setup.py
- src/libertem/executor/dask.py
- src/libertem/executor/inline.py
- src/libertem/io/dataset/hdf5.py
- src/libertem/io/dataset/seq.py
- src/libertem/preload.py
- tests/io/datasets/test_hdf5.py
- tox.ini
Actually use libertem.preload, it got lost when libertem-worker
was established.
List of modules to try importing to be expanded!
Parts of this should also be ported to #1158
> Preload known HDF5 plugins automatically.

- docs/source/changelog/misc/docker.rst
- docs/source/deployment/clustercontainer.rst
- docs/source/install.rst
The old one requires a login and might only work for members of the LiberTEM org on Docker Hub...
> Replace docker hub link with a public one

- benchmarks/io/test_k2is.py
- src/libertem/common/container.py
- src/libertem/io/dataset/base/dataset.py
- src/libertem/io/dataset/base/tiling_scheme.py
- src/libertem/io/dataset/memory.py
- src/libertem/udf/masks.py
Micro-optimization in the `ApplyMasksUDF`: directly re-use `Slice` objects from the `TilingScheme` instead of re-creating them using `discard_nav`. I noticed this when profiling something for #1159.
When using our usual test data, it is a bit hard to measure; even with the inline executor and multiple rounds, the numbers are not stable; I could cherry-pick a run that is faster by 500ms, or one that is exactly as fast as before - we still have some work to do here...
When running a test script on a large (~200GiB) test file, it can be measured more easily:
Before (sum/mean/min/max):
```
total: [75.06046856753528, 15.012093713507056, 14.906086668372154, 15.101721707731485]
```
After (sum/mean/min/max):
```
total: [73.61619642749429, 14.723239285498858, 14.58340313937515, 14.796591619960964] …
```
> ApplyMasksUDF: re-use Slice objects from TilingScheme

- docs/source/changelog/features/new-udfmeta-attrs.rst
- src/libertem/common/container.py
- src/libertem/io/dataset/base/tiling_scheme.py
- src/libertem/udf/base.py
- src/libertem/udf/masks.py
- tests/udf/test_simple_udf.py
They are meant as a direct replacement of accessing the `DataTile` attributes directly, and serve as an official interface for this functionality, which also works with cupy.
In addition, removes a now-redundant `UDFMeta` recreation in the `UDFRunner`, which was needed before to set the tiling scheme.
Fixes #1166
> Add `UDFMeta.sig_slice` and `UDFMeta.tiling_scheme_idx`

- src/libertem/common/numba/__init__.py
- src/libertem/corrections/detector.py
- src/libertem/io/dataset/base/backend_buffered.py
- src/libertem/io/dataset/base/backend_mmap.py
- src/libertem/io/dataset/base/roi.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/udf/stddev.py
This commit was extracted from #1158 as it is independent but touches a number of files. The original commit message is:
It turns out that tiling slows down the threaded case. This
change releases the GIL for more parts of the LiberTEM internals.  The
float32 case uses a very large single tile for the partition and shows
the difference.
Rebased from @uellue commit d0037924
> Release GIL in more Numba methods

- docs/source/changelog/features/mib-quad-raw.rst
- docs/source/contributing.rst
- examples/Introduction to UDFs.ipynb
- setup.cfg
- src/libertem/io/dataset/base/backend_buffered.py
- src/libertem/io/dataset/base/fileset.py
- src/libertem/io/dataset/base/tiling.py
- src/libertem/io/dataset/frms6.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- tests/io/datasets/test_mib_decoders.py
- tests/io/datasets/test_mib_decoders_quad.py
- tests/udf/test_udf_runner.py
- tox.ini
For now, we support `1x1` and `2x2` layouts, with 1bit and 6bit counter depth. Support for other layouts and bit depths can be added on demand. Fixes #1135.
> Add support for some RAW MIB Quad formats

- tests/udf/test_memleak.py
Locally, the first "real" round was still varying a lot in memory use, let's see if it's the same issue on Mac OS X
> Try to fix robustness of memleak test: use 2 rounds of warmup

- src/libertem/api.py
- tests/viz/test_viz_base.py
Don't skip intermediate results if they will be required
for plotting.
No changelog since this is a regression introduced after 0.8.
> Re-enable live plotting

- src/libertem/utils/async_utils.py
- tests/utils/test_async_utils.py
`StopIteration` seems to be used in the guts of async generators, from PEP-525:
The protocol requires two special methods to be implemented:
An __aiter__ method returning an asynchronous iterator.
An __anext__ method returning an awaitable object, which uses StopIteration exception to "yield" values, and StopAsyncIteration exception to signal the end of the iteration.
This apparently means raising `StopIteration` anywhere in async code just generates an error, which also can't really be caught by user code... *sigh*
This is a partial fix for #1200 for defense in depth, the K2IS-specific parts will follow in a separate PR.
> sync_to_async: shield async code from `StopIteration`

- azure-pipelines-data.yml
This used to be the case for the VM-based cloud agents, but not for our current setup... Also actively remove credentials afterwards.
> Fix deploy_docs: don't assume ~/.ssh doesn't exist

- docs/source/changelog.rst
- src/libertem/common/buffers.py
- tests/udf/test_aux_data.py
- tox.ini
Closes #1203
I'm not sure what the reason for the special treatment was, but it seems that removing it fixes this bug, and tests still pass.
The special treatment was part of the original implementation of tiled processing in 992fdb621
> Correct shape of buffer views for tile depth 1

- azure-pipelines-data.yml
Update the `linux_tests`, `numba_coverage` and `docs-check` jobs
> Fix: properly run `tox -r` if the recreate checkbox was checked

- azure-pipelines-data.yml
This was inadvertendly removed in 4d62c2ad, but as the CI env doesn't
start from zero (for performance reasons), it didn't cause a problem
until now.
> Fix: re-add missing `pip install tox`

- azure-pipelines-data.yml
Update from old LTS version (12) to the current one (16). This is important to get a `npm` version that is recent enough for the new lockfile version.
Also updates the CI script to use `npm ci` instead of `npm install`, to always install the locked versions.
> Update nodejs version in CI to current LTS

- docs_requirements.txt
A new release containing the relevant fixes has been pushed.
> No longer install hdbscan from git for docs

- conftest.py
- pytest.ini
- test_requirements.txt
- tests/template/test_com_template.py
The changes here at least make `tests/server` run through; the ones in `tests/template` ~still hang indefinitely somewhere, after
the main test code times out. Possibly the hang is in the added code for event loop cleanup, like `loop.shutdown_asyncgens` and `loop.shutdown_default_executor`?~ Updating to current `pytest` and `pytest-asyncio` fixed the hang in there, too.
Fixes #1187
> Fixes for the current pytest-asyncio

- conftest.py
- docs/source/changelog/bugfix/non-square-plots.rst
- src/libertem/api.py
- tests/viz/test_bqp.py
Fixes issues with non-square plots
> Don't use squeezed damage for plotting

- src/libertem/udf/base.py
- tests/udf/test_simple_udf.py
Refactoring to allow more specialized `UDFRunner` subclasses.
> Split `UDFPartRunner` off `UDFRunner`

- azure-pipelines-data.yml
- docs/source/changelog/features/python-310.rst
- docs/source/install.rst
- setup.py
- tox.ini
- Remove pyfftw special-case from tox.ini
- Add py310 tox env
- Fix comment: Python version in debian stable is 3.9
- Add azure devops jobs for Python 3.10 in the matrices for data_tests
and linux_tests
Fixes #1133
> Add support for Python 3.10 in CI

- docs/source/changelog/misc/cuda_workers.rst
- src/libertem/executor/dask.py
- tests/test_local_cluster.py
Fixes the case where a CUDA worker spec with the same name squashes the previous worker spec in the `workers_spec` dictionary. This enables spawning multiple CUDA workers on the same GPU via `cluster_spec`, which currently has to be done by manually by editing the returned dictionary (now more challenging due to tracing setup!!).
The first cuda worker created on each device has an unmodified name ('default-cuda-0'), subsequent workers on the same device are named ('default-cuda-0-0', 'default-cuda-0-1', 'default-cuda-0-2' etc).
Closes #1225
> Ensure unique CUDA worker names

- docs/source/changelog/misc/pick_free_port.rst
- src/libertem/web/cli.py
- src/libertem/web/server.py
Closes #1184 
Change the way the server binds to a port `server.bind_socket()` rather than `server.listen()` so that we can explicitly create the socket ourselves and set/access its port. Sets a random port if the default/choice by using the alias port 0 when binding to the socket. Required returning the socket object from server.py:main() so that server.py:run() can launch the correct address in the browser tab.
Tested running/using the server on Windows and Linux. I think there is no direct testing of the server.py:main/run, though, I will  try to look into that.
> Pick random port for libertem-server if default/choice not available

- MANIFEST.in
- docs/source/changelog/misc/change_manifest.rst
In response to #1271 and #1275, adjusts `MANIFEST.in` to include:
- tests/
- pytest.ini
- conftest.py
- tox.ini
- test_requirements.txt
and excludes:
- *.pyc
- *.nbc
- *.nbi
- `__pycache__/`
Tested by installing from the .whl output of `python -m build` into fresh py39 and py310 environments. Confirmed that the source distribution does not contain any of the cache files.
Tested also that the web client files are correctly packaged.
Bundle size has dropped from 4.1 MB to 3.0 MB even when including 800 KB of test files !
This should allow running tests when packaging for conda-forge.
Closes #1275
> Include tests, Remove pyc / nbc / nbi files in source distribution

- nbval_sanitize.cfg
Should fix the following error:
2022-06-27T11:41:19.3546591Z [94mTraceback:[0m
2022-06-27T11:41:19.3547258Z [94m mismatch 'stdout'[91m
2022-06-27T11:41:19.3547473Z
2022-06-27T11:41:19.3547910Z  assert reference_output == test_output failed:
2022-06-27T11:41:19.3548106Z
2022-06-27T11:41:19.3548591Z   'CPU_TIMES\nWALL_TIME\n' == 'CPU_TIMES1mi...LL_TIME1min\n'
2022-06-27T11:41:19.3549050Z   - CPU_TIMES1min
2022-06-27T11:41:19.3549415Z   ?          ----
2022-06-27T11:41:19.3549709Z   + CPU_TIMES
2022-06-27T11:41:19.3550078Z   - WALL_TIME1min
2022-06-27T11:41:19.3550428Z   ?          ----
2022-06-27T11:41:19.3550858Z   + WALL_TIME
... and related errors for the CPU_TIMES output
> Tweak nbval regex once again

- docs/source/changelog/bugfix/params_get.rst
- src/libertem/udf/base.py
- tests/udf/test_simple_udf.py
Closes #1284 , catches both the existing `KeyError` and now also `AttributeError`.
Also added a test case for the method for coverage.
Note that there is a change in behaviour here: before, calling `.get` on a missing key would raise, now it will silently return None. This is consistent with the behaviour of `dict.get()` but is a (very small) API change for LiberTEM.
> Fix for `UDFData.get()` on missing key

- setup.cfg
- tests/io/datasets/test_npy.py
- tox.ini
Fixes #545 
These days, `pytest-cov` "just works" with threading and multiprocessing, but only if there is no additional direct configuration of `coverage`. This should improve coverage reporting from our integration tests, and is also a good preparation for #1267 
Snuck in a fix for npy tests not working well with `pytest-xdist`.
> Fix coverage for multiprocessing

- src/libertem/masks.py
- src/libertem/utils/generate.py
- tests/test_utils.py
See https://github.com/scipy/scipy/releases/tag/v1.8.0 - "Clear split
between public and private API"
2022-07-23T09:36:06.8980821Z .tox/py310/lib/python3.10/site-packages/libertem/masks.py:12
2022-07-23T09:36:06.8981593Z   /azp/agent/_work/1/s/.tox/py310/lib/python3.10/site-packages/libertem/masks.py:12: DeprecationWarning: Please use `coo_matrix` from the `scipy.sparse` namespace, the `scipy.sparse.coo` namespace is deprecated.
2022-07-23T09:36:06.8982174Z     MaskArrayType = Union[np.ndarray, sp.coo.coo_matrix, sp.dok.dok_matrix]
2022-07-23T09:36:06.8982378Z
2022-07-23T09:36:06.8982821Z .tox/py310/lib/python3.10/site-packages/libertem/masks.py:12
2022-07-23T09:36:06.8983586Z   /azp/agent/_work/1/s/.tox/py310/lib/python3.10/site-packages/libertem/masks.py:12: DeprecationWarning: Please …
> Fix scipy deprecation warnings

- scripts/release
Probably fixes #414
For some reason, `repo.get_release("continuous")` does not return a release object, which is probably the reason we had leftover releases. List and filter instead.
Scheduled for 0.11 as I don't want to touch the release script shortly before 0.10.
> Delete continuous releases using the list endpoint

- docs/source/changelog/bugfix/pipelined-keyerror.rst
- src/libertem/executor/pipelined.py
- tests/executor/test_pipelined.py
Fixes `KeyError` on a UDF run after an error downstream, for example in the consumer of `Context.run_udf_iter`.
> `PipelinedExecutor`: be resilient against bad values in response queue

- docs/source/changelog/bugfix/pipelined-timeout.rst
- src/libertem/executor/pipelined.py
Tested in the DECTRIS live acquisition with a missing frame that
causes an assertion error.
> Don't freeze when missing in-flight tasks

- docs/source/changelog/bugfix/pipelined-kill-36.rst
- src/libertem/executor/pipelined.py
- tests/executor/test_pipelined.py
Python 3.6 doesn't have `Process.kill`, emulate using `TerminateProcess` or `os.kill`.  Also fix logic that determines when to call `Process.kill`.
> Fix worker killing on Python 3.6

- azure-pipelines-data.yml
Updates the Azure pipelines definition for `test live_integration` to include the `libertem-live[dectris]` optional extra.
~~What I don't know is if running `/azp run libertem.libertem-data` here will use the updated file or the already-defined file?~~
> Add [dectris] option to LiberTEM-live test install

- docs/source/changelog/misc/slice_shape_optim.rst
- src/libertem/common/buffers.py
- src/libertem/common/shape.py
- src/libertem/common/slice.py
Addresses #1313 at least for the method `BufferWrapper.get_contiguous_view_for_tile`.
I don't have an infallible way to prove the performance advantage yet, but comparing cProfiles for before/after this change, on the same data/tiling as in #1313 but as a dense `MemoryDataSet` + `InlineJobExecutor`:
Before:
After:
`get_contiguous_view_for_tile` doesn't show in the _After_ image, but the time spent in this function is:
compared to 44% of `run_for_partition` time before these changes.
Summary of changes / rationale:
- Where possible avoid calling the `Shape` and `Slice` constructors, which happens a lot throughout the code and adds overhead everywhere.
- Adds `NavOnlyShape` and `SigOnlyShape` with optimised constructors + methods, as sub-classes of `Shape`
- Don't construct `Slice` objects …
> (Partially) optimise Shape/Slice

- tests/udf/test_simple_udf.py
- tests/utils.py
Addresses #1282.
Overrides `UDF._do_get_results(self)` on `ValidationUDF` to verify that every frame is fully tiled and visited during the processing, taking into account the ROI (if provided).
~~As tiled processing visits each frame potentially multiple times, the raw 'seen'/'visited' values can be >= 1, here I've made the assumption that the tiling code is robust/correct so I don't verify that each pixel of each frame was seen, only that each frame was split in to the same number of tiles (or never seen at all in the partition).~~
~~Needs test cases to verify this actually raises when a dataset is not visited completely, which will require some kind of deliberately broken over-ride implementation of `get_tiles`.~~
> ValidationUDF tracks which data has been 'seen'

- docs/source/changelog/misc/square_nav_auto_web.rst
- src/libertem/common/math.py
- src/libertem/io/dataset/k2is.py
- src/libertem/io/dataset/mib.py
- src/libertem/io/dataset/mrc.py
- src/libertem/io/dataset/seq.py
- src/libertem/io/dataset/tvips.py
- tests/common/test_math.py
- tests/executor/test_pipelined.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_mrc.py
Fixes #1309 
Required updating tests for MIB and MRC `detect_params`. Quite difficult to test this for the other datasets affected as we don't necessarily have data recorded on a square nav grid (apart from mocking the data).
> Choose square `nav_shape` if detected `num_frames` is square (web-only)

- docs/source/changelog/misc/int_cluster_spec.rst
- src/libertem/executor/dask.py
- src/libertem/executor/pipelined.py
- src/libertem/executor/utils/__init__.py
- tests/executor/test_pipelined.py
- tests/test_local_cluster.py
Closes #1294 . Covers `DaskJobExecutor` and `PipelinedExecutor`.
In order to round-robin assign CUDA ids we need to call `detect()` within the `make_spec` function (I delayed the import). I also added a warning when creating CUDA workers on a system with no detected CUDA devices.
> Allow integer arguments for `cluster_spec`

- examples/Introduction to UDFs.ipynb
- nbval_sanitize.cfg
- src/libertem/io/dataset/base/partition.py
- src/libertem/io/dataset/memory.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_ser.py
- tests/io/test_base.py
- tests/udf/test_by_partition.py
- tests/udf/test_simple_udf.py
Closes #1335 . Uses the implementation with `np.linspace`.
This required making a change to `MemoryPartition.get_tiles()` to propagate `tiling_intent` where available, which I think was actually a bug/oversight.
I also had to modify a number of test cases (including core tests in `tests/udf`) because they had been coded both for the old implementation of `make_slices` and the old implementation of `MemoryPartition.get_tiles()`. It seems like there were a few cases which previously were expected to raise with `pytest.raises` but now actually pass as with the other parametrizations of those tests. These changes should be thoroughly reviewed!
> `make_slices` obeys `num_partitions` (avoids hanging frames)

- docs/source/changelog/bugfix/pipelined-startup-err.rst
- src/libertem/executor/pipelined.py
- tests/executor/test_pipelined.py
Fixes #1340 
Increase `startup_timeout` and throw a user-friendly exception:
```
Traceback (most recent call last):
File "/tmp/work/t.py", line 4, in <module>
executor = PipelinedExecutor.make_local(startup_timeout=0)
File "/home/alex/source/LiberTEM/src/libertem/executor/pipelined.py", line 711, in make_local
return cls(spec=spec, **kwargs)
File "/home/alex/source/LiberTEM/src/libertem/executor/pipelined.py", line 654, in __init__
self._pool = self._start_pool()
File "/home/alex/source/LiberTEM/src/libertem/executor/pipelined.py", line 681, in _start_pool
raise RuntimeError(
RuntimeError: Timeout while starting workers, might need to increase `startup_timeout` (is 0s)
```
* [N/A] I have included the [rebuilt …
> `PipelinedExecutor`: handle alow startup more gracefully

- tox.ini
New `pint` release broke importing from `pint.unit`, which is what hyperspy uses
> pin pint to <0.20

- docs_requirements.txt
- test_requirements.txt
hdbscan had a release that should be compatible with current joblib.
> Unpin joblib

- .gitignore
- tox.ini
Adds a command `tox -e notebooks_gen` which regenerates the example notebooks into a folder `examples/generated/`. This is fine for all notebooks except `live-plotting.ipynb` which requires us to use an interactive matplotlib backend (currently `nbagg`). For now I can't think of an easy way to auto-generate this particular notebook. The new notebooks go in `generated/` so that the command can be run multiple times before a 'final' copy + commit of the updated notebooks is made in `examples/`.
The tox config essentially copies `tox -e notebooks` but also installs `pyopencl` and `graphviz` to support `hyperspy-integration.ipynb`. This won't be robust to graphviz install issues (but does work on the server where we have access to the example data).
I also set 
```
PYTHONWARNINGS=ignore …
```
> Generate notebooks from tox command

- tests/io/datasets/test_frms6.py
- tests/io/datasets/test_hdf5.py
Fixes #1349. Explicit cleanup for both FRMS6 (~8G) and HDF5 (~3G) tests.
> Add explicit cleanup for potentially large temp test data

- MANIFEST.in
Avoids extremely long package build times (and pyroma evaluation time) by explicitly avoiding ever adding `node_modules` to the source dist.
Previously we had these two lines in MANIFEST.in:
```
graft client
prune client/node_modules
```
which during building would first add, then remove node_modules. On some systems this can take up to a minute, and is done even during `pyroma` which means it happens on every commit (with pre-commit enabled).
NOTE: on my system it seems like `package-lock.json` is included in the dist file, which can be quite large (> 1 MB). If we are building from a clean checkout this would not happen but it's something to be aware of (or we can exclude it explicitly).
> Explicitly add content of client/ in MANIFEST.in

- src/libertem/io/dataset/base/tiling_scheme.py
- tests/io/test_tiling_negotiation.py
> Allow adjust_tileshape() to upgrade to full frames

- src/libertem/executor/pipelined.py
Otherwise, in case of exceptions, it's possible that resources from the handler are not cleaned up properly, leading to leaks.
> `PipelinedExecutor`: move `TaskCommHandler` cleanup to `finally`

- src/libertem/executor/pipelined.py
Forcing gc after each partition is a bit too much, and not worth the stability you get while running the code for one partition. Remove forced/manual GC for now.
> Tweak gc in pipelined executor

- src/libertem/api.py
- tests/test_context.py
With out it, we get an error from the innards of the `UDFRunner`
> Context.run_udf: explicitly check for empty UDF list

- src/libertem/io/dataset/__init__.py
Small change to split the util function for choosing the dataset search order from the `detect()` function. Useful if we want to access this order from another location.
For me doesn't need a changelog entry?
> Split get_search_order in `io.dataset.__init__`

- docs/source/changelog/bugfix/raw_csr_detection.rst
- src/libertem/io/dataset/raw_csr.py
- tests/io/datasets/test_raw_csr.py
Closes #1403 
Guards against by accepting either files with a supported extension, or files less than 1 MB in size with any extension.
~~Need to add a regression test case.~~
* [NA] I have added/updated documentation for all user-facing changes
* [NA] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)
> Add guard against too-large files in RawCSRDataSet detect_params

- docs/source/changelog/features/coords-task-data.rst
- src/libertem/udf/base.py
- tests/udf/test_coords.py
As an alternative to #1210, this keeps the option open to have different partition slicing schemes in the future, that cannot be modeled by a simple `Slice` object. For most applications, it should be sufficient to have the coordinate list available for the partition.
This does not yet add support for accessing coordinates in `preprocess`, as that is also called per-dataset, and the coordinate code would need substantial changes to support this.
> Make sure coordinates are available in `get_task_data`

- docs/source/api.rst
- docs/source/changelog/misc/make_with_workers.rst
- examples/basic.py
- src/libertem/api.py
- src/libertem/exceptions.py
- src/libertem/executor/concurrent.py
- tests/executor/test_functional.py
- tests/test_context.py
Adds the interface described here: https://github.com/LiberTEM/LiberTEM/pull/1353#issuecomment-1476394109 to `lt.Context.make_with(..)`.
Some of the added code would be temporary until all the executors accept something resembling a `ResourceSpec` created by `make_with`. This only implements the user-facing part and has some glue code to handle the different cases, the idea being it might be useful to have a working prototype!
> `Context.make_with` number of workers interface

- setup.py
This works around:
- Breakage in `hdbscan` https://github.com/scikit-learn-contrib/hdbscan/issues/597 caused by API changes in `scikit-learn` 1.3.0. Needs a new `hdbscan` release to be fixed.
- Brakage in `dask==2023.6.1`, hopefully fixed in the next release via https://github.com/dask/dask/pull/10385 or similar
> Pin `scikit-learn` to `<1.3.0` and `dask!=2023.6.1`

- docs/source/changelog/features/udf-cancellation.rst
- docs/source/udf/basic.rst
- src/libertem/api.py
- src/libertem/common/executor.py
- src/libertem/exceptions.py
- src/libertem/executor/pipelined.py
- src/libertem/udf/__init__.py
- src/libertem/udf/base.py
- tests/executor/test_inline.py
- tests/executor/test_pipelined.py
- tests/test_context.py
Previously, the `JobCancelledError` was bubbling up to the user, which is not really part of the public API, and also caused a queue drain in the `PipelinedExecutor`. This PR replaces it with a properly documented `UDFRunCancelled` exception.
> Properly expose UDF cancellation

- .github/workflows/ci.yml
- setup.py
This reverts commit 917a1fbe33adf78fe66d7f0c8c57547d16a46f27.
Also require current `sparseconverter` version, which should fix #1467
> Revert "Pin Python 3.7 version in CI for macos-latest"

- docs/source/changelog/features/com_udf.rst
- docs/source/conf.py
- docs/source/reference/api.rst
- docs/source/reference/udf.rst
- docs_requirements.txt
- src/libertem/analysis/com.py
- src/libertem/executor/delayed.py
- src/libertem/udf/base.py
- src/libertem/udf/com.py
- src/libertem/udf/masks.py
- tests/executor/test_delayed.py
- tests/udf/test_com.py
Adds `COMUDF`, continued from #1392 .
Notes:
- The default analysis parameters have been lifted into the definition of the `COMParams(NamedTuple)`, which makes the default functionality a bit clearer without digging into the code of `get_task_data`.
- Added a `@classmethod` `COMUDF.with_params(...)` to allow construction of a UDF with the desired `COMParams`, but mainly to give a clear place where the behaviour of each parameter is documented.
- Added a `raw_com` result buffer for the position of the CoM in the coordinate system of the frame - i.e. COMUDF returns the CoM, in addition to the *shift* in the CoM + field-derived results.
- Documented all of the result buffers in the docstring of `COMUDF`, again for visibility.
Two ideas:
- Any enthusiasm for renaming the UDF `CoMUDF` ? It …
> Add COMUDF

- setup.py
We use `python -m build` these days, which uses PEP517 isolated builds. This means the `build_py` command is executed not on the source tree, but on a copy built from the sdist. There, we can't get the git revision anymore...
It also turns out that the baked revision in the sdist was written to a bad path (libertem/_baked_revision.py vs
src/libertem/_baked_revision.py), and by fixing that, the wheel now also contains the correct revision.
> Fix _baked_revision building

- tests/server/test_dataset.py
As they are not run in CI, these tests didn't get updated for #1475 and had an out-of-date assertion:
- `test_initial_state_after_reconnect`
- `test_prime_cache`
> Fix web API test cases

- src/libertem/io/fs.py
- tests/io/test_io_fs.py
Fixes #1491 
Adding a test case for this is nontrivial, still thinking about it.
> Catch `PermissionError` when doing `os.stat()` on file or directory

- docs/source/changelog/misc/hashable_shape.rst
- src/libertem/common/shape.py
- tests/common/test_shape.py
Brings `Shape` into line with `Slice` by adding the `__hash__` method.
> Hashable `Shape`

- setup.py
Work around https://github.com/pydata/numexpr/issues/449 and remove outdated pins (`scikit-learn`, `pycodestyle`)
> Update dependency pins

- docs/source/changelog/features/convert_transposed.rst
- docs/source/reference/dataset.rst
- src/libertem/contrib/convert_transposed.py
- src/libertem/io/dataset/dm_single.py
- src/libertem/udf/record.py
- tests/io/datasets/test_dm_single.py
- tests/io/test_convert_transposed.py
Adds converter for `(sig, nav)` DM4 files to `(nav, sig)` NPY files so that these can be processed using LiberTEM.
Add a single user-facing function at `libertem.contrib.convert_transposed.convert_dm4_transposed`.
Uses `process_partition` and a modified `RecordUDF` to load blocks of the file, generally avoiding the multiple-traversal / page fault issue explored in #1328.
This  converts the data to a numpy file, but I think it would be possible to extend it to create a new, c-ordered DM4 file with the same tags / structure + the special flag to denote a c-ordered file.
> Converter for `(sig, nav)` DM4 files

- docs/source/changelog/features/gui-resource-cli.rst
- docs/source/usage.rst
- src/libertem/web/cli.py
- src/libertem/web/connect.py
- src/libertem/web/server.py
- src/libertem/web/state.py
- tests/server/test_state.py
Closes #1419 
Adds the following CLI options:
- `-c / --cpus <int>` specify the number of CPU workers
- `-g / --gpus <int>` specify the number of GPU workers
- `-o / --open-ds <path>` specify the dataset to open via URL fragment (#1518 )
Also improves the log message for the connection address (more prominent, adds a version with hostname), and improves the help text for `--insecure` (#1534 ).
> Specify resources, load dataset from `libertem-server` CLI

- docs/source/api.rst
- docs/source/changelog.rst
- docs/source/changelog/misc/exceptions.rst
- docs/source/reference/api.rst
- docs/source/reference/udf.rst
- docs/source/udf/basic.rst
- scripts/licensecheck.py
- src/libertem/api.py
- src/libertem/common/exceptions.py
- src/libertem/exceptions.py
- src/libertem/io/dataset/base/tiling_scheme.py
- src/libertem/udf/base.py
- tests/executor/test_functional.py
- tests/executor/test_inline.py
- tests/executor/test_pipelined.py
- tests/io/test_tiling_negotiation.py
- tests/test_context.py
- tests/udf/test_buffer_declarations.py
- tests/udf/test_simple_udf.py
Import to `libertem.io.dataset.base.tiling_scheme.py` was added since last release.
Refs #1542 
> Move exceptions to libertem.common

- src/libertem/common/backend.py
- src/libertem/executor/pipelined.py
- src/libertem/io/dataset/mib.py
- src/libertem/preload.py
- tests/io/datasets/test_mib.py
- tests/io/test_many_files.py
First stab at optimizing the header-reading code of `MIBDataSet` to use a `ThreadPoolExecutor` when reading a 'large' number of files, particularly useful when opening a dataset of many small files over the network.
The number of workers for this executor is quite sensitive, and I need to do more testing. For now it's limited to `2` on linux and `0.5 * num_cpu` on Windows based on what I've seen so far. I'll try to do some benchmarking tomorrow (made a bit more tricky because of filesystem caching / remote storage server caching).
Also adds a specialised `get_num_partitions` which tries to guess a `num_partitions` value which won't break the `NOFILE` limit for a process (assuming we are running in a process-based executor) on linux (only). There's a lot to improve in this part, but it …
> Optimise `MIBDataSet` to read headers in parallel + respect ulimit NOFILE

- src/libertem/web/state.py
- tox.ini
Fix snooze task cancellation being called from the wrong thread (which was caught by this change).
> Run `web_api` tests with `PYTHONASYNCIODEBUG=1`

- src/libertem/web/cli.py
- src/libertem/web/server.py
- src/libertem/web/state.py
- tests/server/test_cli.py
- tests/server/test_startup.py
Fix for the following exception at startup:
```
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/runpy.py", line 197, in _run_module_as_main
Line:     return _run_code(code, main_globals, None,
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/runpy.py", line 87, in _run_code
Line:     exec(code, run_globals)
Line:   File "/home/alex/source/LiberTEM/src/libertem/web/cli.py", line 109, in <module>
Line:     main()
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
Line:     return self.main(*args, **kwargs)
Line:   File "/home/alex/miniconda/envs/libertem/lib/python3.9/site-packages/click/core.py", line 1055, in main
Line:     rv = self.invoke(ctx)
Line:   File …
```
> Fix "RuntimeError: no running event loop" at `libertem-server` startup

- azure-pipelines-data.yml
Otherwise, builds for `master` won't properly submit their coverage.
> Codecov needs the token in azure, too

- tests/io/datasets/test_raw_csr.py
Can't have randomly generated parametrize values, as that influences the test names, which have to be consistent across pytest-xdist workers.
This fixes things like `pytest tests/ -m "slow and not dist" -n 12`
> Fix `test_raw.csr.py::test_reshape_sync_offset` w/ pytest-xdist

- examples/live-plotting.ipynb
- setup.py
- src/libertem/viz/mpl.py
- tox.ini
The newest versions of jupyterlab and notebook don't support the `nbagg` backend anymore. Instead the `widget` backend is supposed to be used: https://matplotlib.org/stable/users/explain/figure/interactive.html#jupyter-notebooks-jupyterlab
With this change the `widget` backend shows and updates the plots live as it is supposed to. It also uses the recommended live drawing functions for matplotlib:
https://matplotlib.org/stable/users/explain/figure/interactive_guide.html#explicitly-spinning-the-event-loop
> Make sure live plots work with the widget backend

- docs/source/changelog.rst
- docs/source/changelog/misc/field-components.rst
- packaging/creators.json
- src/libertem/udf/com.py
- tests/udf/test_com.py
This is only a small change in the :class:`~libertem.udf.com.CoMUDF` class. It exposes the y- and x-components of the `field` result. The reason is so that they are more easy to plot and access, which is already shown to be useful in cases where the other results do not give good information. For example in my case where the entire dataset is magnetized with same magnitude, but different orientation.
> Exposed Y and X field shifts in CoMUDF

- conftest.py
- setup.py
- src/libertem/executor/utils/dask_inplace.py
- src/libertem/io/dataset/blo.py
- src/libertem/io/dataset/tvips.py
- src/libertem/viz/bqp.py
- tests/executor/test_dask_inplace_wrapper.py
- tests/test_context.py
- tests/viz/test_gms.py
- tests/viz/test_mpl.py
Part of #1414 
- Fixes usage of `pkg_resources` → `importlib_metadata`
- Fixes some deprecation warnings added in numpy 1.25 
- Fixes wrong usage of `bqplot`
- Ignore expected warnings thrown by our own code (plotting related mostly)
> Reduce number of warnings from tests

- docs/source/changelog/bugfix/windows-js-mimetype.rst
- src/libertem/web/cli.py
Fixes #1612. To reproduce this: 
- Set `HKEY_CLASSES_ROOT\.js\Content Type` to `text/plain` instead of `application/javascript`
- Install LiberTEM without this PR
- Start `libertem-server`
- Note that chrome/firefox give you an error message in the developer tools console, and that the `.js` file is transferred as `text/plain` (see network tab, possibly needs a reload), and that the GUI does not load
- After applying this PR, and restarting `libertem-server`, the GUI should load properly
- Restore the registry key to the proper value
> Fix #1612 - wrong MIME type for .js files

- src/libertem/web/server.py
Closes #1616 
Seems like the web server also needs coaxing into using `WindowsSelectorEventLoopPolicy`. Without this change we had a `ProactorEventLoop` despite the `Selector` policy being returned from `asyncio.get_event_loop_policy()` (??).
Probably needs more thought later, but if you can check on your Windows 11 machine @uellue we could merge as a quick fix? I've checked this now works on Windows 10, Windows Server 2016 and a Ubuntu Server 20.
This was not caught by the smoke `test_cli.py` case because it only checks for a synchronous `log.info`, we could make it actually `curl` the server address to check if we actually get a response!
> Adjust event loop on Windows when launching libertem-server

- docs/source/changelog.rst
- docs/source/changelog/bugfix/com.rst
- docs/source/changelog/features/valid-data-masking.rst
- docs/source/udf/advanced.rst
- src/libertem/api.py
- src/libertem/common/buffers.py
- src/libertem/executor/delayed.py
- src/libertem/executor/utils/dask_buffer.py
- src/libertem/udf/base.py
- src/libertem/udf/com.py
- src/libertem/viz/base.py
- tests/udf/test_com.py
- tests/udf/test_valid_mask.py
- tests/viz/test_mpl.py
- tox.ini
Makes the "valid nav mask" available in UDFs, and propagates it to results.
Closes #1473, closes #1449
> Valid data masking

- docs/source/changelog/bugfix/empad-scan-params.rst
- src/libertem/io/dataset/empad.py
- tests/io/datasets/test_empad.py
For some EMPAD data sets, the raw file corresponds to the shape of the scan parameters with `mode="search"`, not `mode="acquire"`. That means we were expecting more data than actually available.
Note that this means we are more strict in what we accept, in particular this checks (if we are opening via the XML file) that the raw file is exactly as large as specified in the XML file (one of the two `scan_parameters`). Previously, it was probably possible to have a raw file that is larger than the specified scan in the XML file, and we would have probably accepted that.
Fixes #1617 
@uellue is the `Magical_DataSet` going to stay in our test data, or should we extract an example file?
> Fixup for malformed EMPAD data

- src/libertem/web/browse.py
- src/libertem/web/dataset.py
Setting the snooze timeout very low, for example by starting with `libertem-server --snooze-timeout 0.001`, exposes some issues which this commit fixes, namely that the
executor snoozes before `get_fs_listing`/`detect` finish running.
It's not recommended to set the snooze timeout so small, but this change should increase stability in these cases - also possibly useful in cases where a lot of time passes between getting the executor and when the actual function is called, for example when the system is put to sleep, or possibly in case of forward jumps in time (?)
Refs #1576 - lower-level keep-alive would prevent this kind of issue completely.
> Ensure liveness of executor for some utility endpoints

- conftest.py
- docs/source/releasing.rst
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_empad.py
- tests/io/datasets/test_frms6.py
- tests/io/datasets/test_k2is.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_missing.py
- tests/io/datasets/test_mrc.py
- tests/io/datasets/test_npy.py
- tests/io/datasets/test_raw.py
- tests/io/datasets/test_seq.py
- tests/io/datasets/test_ser.py
- tests/io/datasets/test_tvips.py
Adds test cases to display a range of error messages from datasets when supplied with bad parameters. Responds to this comment https://github.com/LiberTEM/LiberTEM/pull/1625#pullrequestreview-2024548062
The bad parameter tests don't actually assert that exceptions are or are not raised, the simply store and echo the output for a human to verify (as they would do with the release checklist). The output can be generated with something like:
```
pytest -rA tests/io/datasets/test_missing.py
```
for missing files, and:
```
pytest -rA tests/io/datasets/ -k "test_bad_params"
```
for bad params.
As a result these tests could essentially be marked as "release tests" and only run manually when needed with the "-rA" option.
There is some `pytest` abuse involved, namely the interception of exceptions …
> Missing File / Bad `DataSet` parameters exception messages

- scripts/release
- scripts/requirements.txt
`pkg_resources` is deprecated, so we use the versioning utilities from `packaging` instead.
> scripts/release: use `packaging` instead of `pkg_resources`

- packaging/contributors.json
> Add cigdem to contributors

- docs/source/changelog/features/numpy2.rst
- src/libertem/io/dataset/base/decode.py
- src/libertem/io/dataset/dm.py
- src/libertem/io/dataset/mib.py
- src/libertem/io/dataset/npy.py
- src/libertem/udf/masks.py
- tests/common/test_bufferwrapper.py
- tests/io/datasets/test_blo.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_k2is_uint12.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_mib_decoders.py
- tests/io/datasets/test_seq.py
- tests/io/datasets/test_ser.py
- tox.ini
Fixes #1653
* npy: use `ast.literal_eval` instead of `numpy.lib.utils.safe_eval`
* k2is: fix encode test case; simplify encoder function
* dm: convert image count from `np.uint32` to Python integer, as it is used in arithmetics which might not fit into the original dtype
* mib,raw: update decoders/encoders to explicitly use fitting dtypes for shifted `uint8`s
Note that the notebook tests and the docs checks don't currently run with numpy 2 because of incompatibilities in dependencies (hyperspy->pint and scikit-image), so I've constrained these to `numpy<2` for now.
> Fix compatibility with numpy>=2.0.0

- scripts/creatorlist.ipynb
- tests/analysis/test_analysis_rawfft.py
Not sure what changed... Should not happen
Drive-by deprecation fix
> Attempted fix flaky FFT test on OS X

- pyproject.toml
- tox.ini
This should fix the `uv` dependency resolution issue, where `uv` picks `numpy==2.1.x` and a very old, incompatible `numba` version that wasn't yet constrained to `numpy` versions.
Also add an unconditional `numba` pin so installation on newer Python in the future won't try to pick an ancient `numba` version.
Closes #1672
> Pin minimum numba versions for each Python version

- docs/source/changelog/features/blo-16bit.rst
- src/libertem/io/dataset/blo.py
- tests/io/datasets/test_blo.py
Adds support for a new Blockfile format (1.3) which can store image data in 16bit mode.
The implementation is conservative, falling back to the old 8bit assumption if the metadata does not match what we expect.
I have uploaded a test file "Stingray16bit_7_11.blo" into the root of the test data folder in the DMS.
> Add BLO 16bit support

- src/libertem/web/notebook_generator/code_template.py
Follow-up to https://github.com/LiberTEM/LiberTEM/pull/1599
nbagg is not supported anymore in current jupyter versions
> Update code_template.py: widget instead of nbagg

- pytest.ini
- src/libertem/analysis/clust.py
- src/libertem/analysis/point.py
- src/libertem/common/sparse.py
- src/libertem/io/corrections/corrset.py
- src/libertem/io/corrections/detector.py
- src/libertem/masks.py
- tests/corrections/test_detector.py
- tests/io/test_tiling_negotiation.py
- tests/utils.py
Convert to ndarray or use alternative methods.
Also include filter in pytest.ini that makes this deprecation warning an error during tests.
> Fix deprecation warning on sparse.COO coords

- docs/source/changelog/features/roi-helper.rst
- docs/source/udf/basic.rst
- src/libertem/api.py
- src/libertem/io/dataset/base/dataset.py
- src/libertem/udf/raw.py
- tests/io/datasets/test_helpers.py
Usage:
```python
ctx.run_udf(dataset=ds, udf=SumUDF(), roi=ds.roi[0:7, 12:25])  # or any other numpy-supported slicing
```
Means you don't need to manually make a bool array etc. anymore if you want to slice nav in any of the numpy-supported slicing ways.
Feel free to bikeshed the name, haven't put much thought into it.
> Add a helper for generating ROIs from slices

- src/libertem/common/sparse.py
Closes #1373
The rest is a bit specific and would require re-engineering the MaskContainer, ApplyMasksEngine and their use.
Most transition to sparseconverter was already done when fixing the COO coordinate deprecation in #1699.
* [N/A] Only import code that is compatible with MIT license
> Use more sparseconverter

- conftest.py
- tests/analysis/test_analysis_disk.py
Closes #880
The random data from `np.random.randn` is centered around 0, meaning we amplify numerical errors when we sum up. Switching to `np.random.random` and setting usual error bounds fixes the issue.
Switching to float64 also fixed the instability in tests.
> Fix numerical instability

- pyproject.toml
- tox.ini
LiberTEM seems to work with current versions?
Closes #1698
Closes #1523 
> Remove pin of torch

- src/libertem/executor/concurrent.py
- tests/executor/test_functional.py
They were flaky in some of the recent runs, and this PR hopefully resolves that.
* Don't delay the first two tasks, such that it's highly likely they return after the first `handle_task` call, meaning something is yielded and the test code as a change to submit the parameter changes early
* Terminate the test case as soon as the condition is hit, meaning we can add many more tasks without a performance hit in the common case, and in other cases, we make it more likely the test case succeeds, even if it takes a bit longer
* Fix the concurrent executor to actually support being cancelled in the middle of `run_tasks`
> Try to make the scatter tests more robust

- .github/workflows/thorough.yml
As the workflow can't be triggered manually for a pull request, I'll test this one after merging.
> Remove macos-12 from thorough workflow

- tests/io/datasets/test_blo.py
- tests/io/datasets/test_dm.py
- tests/io/datasets/test_mib.py
- tests/io/datasets/test_ser.py
- tox.ini
It seems upstream has sorted this out?
Refs https://github.com/LiberTEM/LiberTEM/issues/1705#issuecomment-2915508963
Run CI pipeline to verify
> Remove pins for NumPy and pint

- .github/workflows/ci.yml
- .github/workflows/thorough.yml
- conftest.py
- tests/server/test_startup.py
The test failed for "thorough", see details in diff and commit message.
Also try fix for tox env name. Let's see what GitHub makes of this!
> Bandaid for weird test failure; hopefully fix tox env name

- pytest.ini
- src/libertem/common/analysis.py
- src/libertem/common/buffers.py
- src/libertem/common/compat.py
- src/libertem/executor/utils/dask_buffer.py
See https://numpy.org/devdocs/numpy_2_0_migration_guide.html#adapting-to-changes-in-the-copy-keyword
> Add copy/dtype kwargs to `__array__` impls
