src/libertem/viz.py
tests/test_viz.py

Signed-off-by: caron <j.caron@fz-juelich.de>
I reused the Colormap3D class from my "Pyramid" project, stripped away all superfluous content and simplified the functionality to work on 2D color encodings.
If you want, I'd like to add some testing, any hints how I should do that :-)?
I can also add the colour encoding at the appropriate locations, if you can point them out to me.

Added viz module with Colormap2D class for directional color encoding.

---

README.rst

Explain STEM as "scanning transmission electron microscopy"

Explain STEM

---

docs/source/architecture.rst

Extended the documentation with info from Issue #14. Closes #14.

Describe mathematical operation for virtual detectors

---

docs/source/install.rst

Included information on how to update LiberTEM from Git. Closes #93.

Information on updating

---

docs/source/install.rst

Installing PyTorch is not necessary, but recommended for optimal performance.

Included information on PyTorch

---

examples/center_of_mass.ipynb

Updated comments for more clarity

Added more comments

---

README.rst
docs/source/reference.rst
docs/source/usage.rst

Moved content between usage.rst and reference.rst. Simple example in usage.rst, API reference in reference.rst
Updated and extended README.rst with more info on our USPs, possible applications and current status.
Checks "update README to reflect the current project status" in Issue #45

Restructured API documentation, updated README

---

README.rst

Add info on operating system support
@sk1p Thx again for your git training! I managed to re-integrate my diverged origin/docs, upstream/master and local docs branch using what you taught me. Nothing lost and a clean pull request! :100:

Update README wit OS support

---

README.rst

Add format support status info

---

.zenodo.json
docs/source/acknowledgments.rst
docs/source/contributing.rst
docs/source/install.rst

* Fix JSON issues with .zenodo.json
* Include fix for conda/pip issues on Windows
* Include instructions to update credits when contributing
* Wording: Contributors instead of authors

Documentation updates

---

.zenodo.json

Hint by @sk1p: Next time python -m json.tool < .zenodo.json

Some more JSON issues

---

README.rst
docs/source/citing.rst
docs/source/conf.py

Updated Zenodo DOI to 0.1.0 release

Zenodo badge updated and included in README; favicon

---

docs/source/install.rst

Short desription and links on how to set up and use a LiberTEM virtual
environment with Juypter and JupyterHub.
Link the built-in venv module of python3 as an alternate method because
virtualenv was somehow buggy on one test system while venv saved the day.

Include info on Jupyter and JupyterHub in docs

---

docs/source/install.rst

To subtly remind users to always check if they are in the right environment. :-)

Minor edit: add (libertem) prefix to shell prompt

---

docs/source/contributing.rst
docs/source/install.rst
docs/source/usage.rst

Leftover dangling sentence
Different shell prompt for Windows
Formatting

Minor fixes on documentation

---

examples/digital-micrograph-basic.py

Update the comments to follow the previous change of the code

Updated comments

---

examples/digital-micrograph-async.py
prototypes/async/async.py
prototypes/digitalmicrograph/components.py
prototypes/digitalmicrograph/digital-micrograph-async.py

This example uses asynchronous processing to re-calculate a virtual detector
image in response to changes of a marker area.
Thank you @sk1p for the async framework and debugging!
TODO: Proper way to end calculation.

Interactive virtual detector example in Digital Micrograph

---

tests/io/test_hdf5.py
tests/io/test_raw.py
tests/test_analysis_com.py
tests/test_analysis_masks.py
tests/test_analysis_raw.py
tests/test_analysis_shapes.py
tests/test_analysis_sum.py
tests/test_local_cluster.py
tests/utils.py

Better random data with guaranteed asymmetry; numerical test

---

.travis.yml

pushing this as a pull requests to test travis integration

[WIP] integrate client tests into CI

---

docs/source/conf.py

Many thanks to the FZJ IT services for the quick response! :-)

FZ Jülich fixed their filter rules

---

setup.py
src/libertem/executor/dask.py

As suggested by @danpf in https://github.com/dask/distributed/issues/2537#issuecomment-466050723
Many thanks @danpf, this seems to work!
Confirmed to work with distributed==1.25.3

Use distributed.Client instead of distributed.asyncio.AioClient

---

docs/source/gsoc.rst

Suggested by @ReimarBauer. Thx!

Skill level and domain knowledge

---

docs/source/gsoc.rst

Suggestion by @terriko https://github.com/python-gsoc/python-gsoc.github.io/pull/76#issuecomment-469482157
Thx! :-)

Include contact persons

---

docs/source/acknowledgments.rst

Now in alphabetical order to have an objective criterion.

Re-ordered acknowledgments, added some new ones

---

src/libertem/api.py
src/libertem/executor/base.py
src/libertem/executor/inline.py
src/libertem/io/dataset/base.py
src/libertem/io/dataset/blo.py
src/libertem/io/dataset/frms6.py
src/libertem/io/dataset/hdf5.py
src/libertem/io/dataset/hdfs.py
src/libertem/io/dataset/k2is.py
src/libertem/io/dataset/mib.py
src/libertem/io/dataset/raw.py
src/libertem/io/dataset/raw_direct.py
src/libertem/io/dataset/ser.py
src/libertem/io/utils.py
src/libertem/web/server.py

This allows CPU-intensive processing to use all resources
even on small files
See https://github.com/LiberTEM/LiberTEM/issues/252#issuecomment-487884110

Have at least as many partitions as cores are available

---

.gitignore
pip-wheel-metadata/libertem.dist-info/top_level.txt
src/libertem/udf/crystallinity.py
tests/udf/test_crystallinity.py

Returns crystallinity map.
Calculates coefficients for each frame: low values for frames (only zero order peak) which belong to amorphous regions, high values for crystalline frames (zero order peak+periodic non zero order peaks)

UDF for crystallinity map calculation

---

src/libertem/executor/dask.py
src/libertem/web/server.py

Closes #359
Root cause is unknown. The workaround is a bit awkward, but works.
To be tested on Unix!

Handle Ctrl-C on Windows

---

examples/digital-micrograph-basic.py
prototypes/digitalmicrograph/digital-micrograph-async.py

* copy() because of DM API changes
* Use EMPAD reader
* FIXME async prototype is currently broken, see Issue #399

Updating DM examples

---

README.rst
docs/source/api.rst
docs/source/architecture.rst
docs/source/contributing.rst
docs/source/index.rst
docs/source/install.rst
docs/source/usage.rst
docs/source/why_python.rst

Thx @sk1p for your review and fixing most issues!
A few smaller fixes
Taking the dev mailing list out of README since nobody is using it.
Closes #410

Docs update follow-up to #404

---

tests/udf/test_blobfinder.py

Try to get a handle on the failing affinematch test in CI

Add debug code to blobfinder test

---

packaging/zenodo-upload.json

ESTEEM3 was added to the Zenodo grant database.
Thx Lars and George from Zenodo support!

ESTEEM3 works now

---

docs/source/contributing.rst

Include review of issues, PRs and release notes in release checklist

---

src/libertem/udf/blobfinder.py
tests/udf/test_blobfinder.py

Edit: No peak_local_max involved, root cause not sure -- numerical error?
> Peak_local_max didn't give the maximum of the corrmap in some border cases,
> likely in a result that is near zero.
Include more fuzzing and better reporting in test
Closes #283

Fixed a glitch where negative peak elevations were possible

---

docs/source/contributing.rst
docs/source/tips.rst
tests/test_analysis_masks.py
tests/udf/test_blobfinder.py

Improve slow tests, instructions for profiling, rewrap

---

docs/source/app/phasechange.rst
docs/source/changelog.rst
docs/source/conf.py
docs/source/contributing.rst
docs/source/index.rst
tox.ini

Changelog in preparation to v.0.2.2

---

docs/source/changelog/features/blobfinder.rst
src/libertem/udf/blobfinder.py

Extract blobfinder change from PR #463

---

docs/source/install.rst
docs/source/references-libertem.bib

It is `conda activate libertem` instead of `activate libertem` now

New BibTeX entry; update conda instructions; rewrap

---

docs/source/changelog/features/preprocess.rst
docs/source/udf/advanced.rst
src/libertem/udf/__init__.py
src/libertem/udf/base.py
tests/udf/test_aux_data.py

This is useful to allocate data structures for `dtype=object` buffers.
Crystallizing PR #458

Implement preprocessing

---

setup.py

Remove pin of distributed

---

docs/source/changelog/features/circular.rst
src/libertem/udf/blobfinder.py
tests/udf/test_blobfinder.py

This is useful to construct feature vectors, or for comparison.
Crystallizing PR #458

Plain circular match pattern

---

.github/PULL_REQUEST_TEMPLATE

Make clear that starting with an incomplete PR is OK.

Lower entry barrier

---

packaging/contributors.json
packaging/creators.json

Provided prototype code for @kruzaeva, co-supervision of @kruzaeva for blobfinder.

Move Knut to creators

---

docs/source/authorship.rst

Improve linking and orientation within the text

Include headline for policy on publications

---

.gitignore
README.rst
docs/source/references-libertem.bib

Cite Colin's new paper; ignore .bib.bak

---

src/libertem/analysis/radialfourier.py

Syntax error fix; link to parameters

---

docs/source/changelog/bugfix/radialfourier.rst
src/libertem/analysis/radialfourier.py
tests/test_analysis_radialfourier.py

Resolve shape mismatch issue with more than one bin.

Bugfix for Radial Fourier Analysis

---

conftest.py
docs/source/app/amorphous.rst
docs/source/changelog/documentation/reference.rst
docs/source/changelog/features/resultset.rst
docs/source/reference/api.rst
docs/source/reference/application.rst
docs/source/reference/internals.rst
src/libertem/analysis/base.py
src/libertem/analysis/com.py
src/libertem/analysis/disk.py
src/libertem/analysis/fullmatch.py
src/libertem/analysis/masks.py
src/libertem/analysis/point.py
src/libertem/analysis/radialfourier.py
src/libertem/analysis/raw.py
src/libertem/analysis/ring.py
src/libertem/analysis/sum.py
src/libertem/api.py
src/libertem/job/base.py
src/libertem/job/masks.py
src/libertem/job/raw.py
tests/test_analysis_base.py

Improve API reference
* Include information on the keys of an analysis result
* Correct formatting issues and a few incorrect return types
Closes #494

Improve API documentation

---

conftest.py
docs/source/app/amorphous.rst
docs/source/reference/app/amorphous.rst
docs/source/reference/app/strain.rst
docs/source/reference/application.rst
src/libertem/analysis/clust.py
src/libertem/udf/FEM.py
src/libertem/udf/auto.py
src/libertem/udf/blobfinder/correlation.py
src/libertem/udf/crystallinity.py
src/libertem/udf/feature_vector_maker.py
src/libertem/udf/logsum.py

Add some `__init__` methods with docstrings, which dramatically improves
use from an interactive shell (`help()` or `MyUDF?`, tab-completion in
jupyter, ...) and IDEs. Fix some types in docstrings, add examples, ...
See #503 for items that still need to be done

Improve documentation for our UDF implementations, refs #503

---

docs/source/changelog/documentation/udf.rst
docs/source/reference/app/strain.rst
src/libertem/analysis/gridmatching.py
src/libertem/api.py
src/libertem/udf/blobfinder/correlation.py
src/libertem/udf/blobfinder/refinement.py

Restructure API, update and complete documentation, remove documentation of internal or unnecessary features. Follow-up to #507, refs #503

Continue work on UDF API reference, refs #503, #507

---

docs/source/app/amorphous.rst
docs/source/references-libertem.bib
src/libertem/analysis/radialfourier.py

Found a reference for Radial Fourier Analysis

---

docs/source/install.rst

Note on issues with Python 3.8

---

packaging/contributors.json
packaging/creators.json

Add Benedikt @unsimulatable, Johannes, Anastasiia; update Colin and Magnus

Update contributors.json and creators.json

---

README.rst
docs/source/contributing.rst
docs/source/debugging.rst
packaging/creators.json

* Move @woozey up in creators.json because of holography UDF
* Link fixes

Finishing touches

---

docs/source/changelog.rst

DOI badge for 0.3.0; use same version format as before

---

docs/source/app/holography.rst
docs/source/app/phasechange.rst
docs/source/reference/app/holography.rst
docs/source/releasing.rst
docs/source/udf/advanced.rst
src/libertem/analysis/base.py
src/libertem/analysis/com.py
src/libertem/analysis/masks.py
src/libertem/analysis/radialfourier.py
src/libertem/analysis/raw.py
src/libertem/analysis/sum.py
src/libertem/job/base.py
src/libertem/udf/base.py
src/libertem/udf/blobfinder/correlation.py
src/libertem/udf/blobfinder/patterns.py
src/libertem/udf/blobfinder/refinement.py
src/libertem/udf/holography.py
src/libertem/utils/generate.py

Use coherent version format

---

src/libertem/udf/holography.py

Formatting and language improvements

---

docs/publications/joss/paper.md

Author list ordered following creators.json

---

.gitignore
docs/publications/joss/paper.bib
docs/publications/joss/paper.md

* Feedback in https://github.com/openjournals/joss-reviews/issues/1962 Thx @labarba
* Cite LiberTEM 0.3.0
* Ignore *.bib.sav
* Formatting

Updates to JOSS paper [skip ci]

---

docs/source/changelog/bugfix/frms6_dist.rst
src/libertem/io/dataset/frms6.py
tests/io/test_frms6.py

We now make sure to only do I/O in methods that are running on worker
nodes. Fixes #519.
Note: as we don't have test data in CI, the included tests are not run in CI yet.

Fix FRMS6 in a distributed setting

---

tests/udf/test_holography.py

Minor change, so no changelog entry etc.
cc. @woozey

test_holography: use tuple for slicing, fixes #529

---

.codeclimate.yml
README.rst

Fixes #305. This only adds a configuration file, specifically to set a tslint configuration file to get rid of [many false positives](https://codeclimate.com/github/LiberTEM/LiberTEM/issues?status%5B%5D=&status%5B%5D=open&status%5B%5D=confirmed&engine_name%5B%5D=tslint) and enable plugins.

Add codeclimate configuration

---

docs/source/authorship.rst

Clarify that list items are ORd together

---

src/libertem/udf/base.py

Is there a reason against using this?

Enable memory mapping for UDFs

---

.codeclimate.yml
docs/source/changelog/features/dtypes.rst
docs/source/changelog/features/udfmasks.rst
docs/source/changelog/misc/udfmasks.rst
docs/source/changelog/obsolescence/jobremoval.rst
docs/source/reference/internals.rst
docs/source/reference/udf.rst
docs/source/udf/advanced.rst
src/libertem/analysis/com.py
src/libertem/analysis/disk.py
src/libertem/analysis/masks.py
src/libertem/analysis/point.py
src/libertem/analysis/radialfourier.py
src/libertem/analysis/raw.py
src/libertem/analysis/ring.py
src/libertem/api.py
src/libertem/common/container.py
src/libertem/job/base.py
src/libertem/job/masks.py
src/libertem/udf/base.py
src/libertem/udf/blobfinder/correlation.py
src/libertem/udf/masks.py
src/libertem/udf/raw.py
tests/test_analysis_masks.py
tests/test_analysis_raw.py
tests/test_mask_container.py
tests/udf/test_pick.py
tests/udf/test_simple_udf.py

Start work towards retiring the Job API #549

Implement the functionality of ApplyMasksJob with an UDF

---

docs/source/tips.rst
docs/source/udf.rst
docs/source/udf/profiling.rst

Adds new documentation on how to use `line_profiler` to profile and optimize your UDF.

Add profiling instructions to docs, fixes #552

---

docs/source/gsoc.rst
docs/source/performance.rst

Start updating for GSoC 2020

---

docs/source/app/holography.rst
docs/source/udf/advanced.rst

Some small doc fixes

---

src/libertem/analysis/radialfourier.py
tests/test_analysis_radialfourier.py

Fix mangled data in RadialFourierAnalysis from recent change to UDF back-end

---

docs/source/gsoc.rst

More on GSoC 2020

---

docs/source/gsoc.rst

Feedback from @warthog9, thx!
See also https://github.com/python-gsoc/python-gsoc.github.io/pull/110/

Clean-up, shortening

---

docs/publications/joss/paper.md

Ported from 86ece012a57231c41b065b059cc2a95e9d4a7139 to JOSS paper

[skip ci] Wording improvement

---

tests/io/test_blo.py
tests/io/test_empad.py
tests/io/test_frms6.py
tests/io/test_hdf5.py
tests/io/test_k2is.py
tests/io/test_mib.py
tests/io/test_raw.py
tests/test_analysis_com.py
tests/test_analysis_shapes.py

Make sure that the functionality is tested with the legacy JOB back-end
and the new UDF back-end for the time being

Test for both JOB and UDF

---

docs/source/changelog/features/blobfinder_corr.rst
src/libertem/udf/blobfinder/correlation.py

Changelog entry for libertem.udf.blobfinder.correlation.get_correlation()

---

docs/publications/nionswift2020/abstract.rst

Hi all,
LiberTEM will be present at the Nion Swift workshop in Berlin, March 2020
This is the first draft for an abstract. I'm not sure how to handle conference contributions with respect to the authorship policy https://libertem.github.io/LiberTEM/authorship.html
In the current draft I've listed the LiberTEM creators and distinguished that from the person who is presenting. Furthermore it is probably a good idea to notify all LiberTEM creators:
@sk1p @kruzaeva @woozey @jan-car @irahulcse @magnunor @cophus @probonopd @ozej8y @jaewshin (Knut via e-mail) @rafaldb
Your feedback is welcome! :-)

Abstract for Nion Swift conference in Berlin, March 2020

---

src/libertem/udf/stddev.py

run_stddev() is recommended instead. :-)

Clarify that the UDF produces raw results and not variance

---

src/libertem/io/dataset/base.py
src/libertem/io/dataset/frms6.py
tests/io/test_dm.py

Fixes test failures for DM and FRMS6

Misc. DataSet fixes

---

docs/source/changelog.rst

 Info on restructuring in changelog

---

docs/source/releasing.rst

Also fixes rc version syntax (no dot before rcN!)

Add versioning note and bump to .dev0 step

---

docs/source/changelog.rst
docs/source/changelog/misc/removeme.rst

... and avoid failure of first changelog item with a dummy one

Zenodo DOI badge for release

---

src/libertem/analysis/clust.py
src/libertem/api.py
src/libertem/io/dataset/__init__.py
src/libertem/utils/async_utils.py
src/libertem/web/base.py
src/libertem/web/dataset.py
src/libertem/web/jobs.py

Initialization is also useful for consumers of the low-level API.

Move DataSet initialization into `load` function

---

docs/source/changelog.rst

Update with new DOI for bugfix release

---

docs/source/changelog/features/progress_bar.rst
setup.py
src/libertem/api.py
src/libertem/udf/base.py
tests/udf/test_simple_udf.py

Add a progress bar with tqdm, closes #612

---

packaging/creators.json
src/libertem/api.py

Added types to libertem.api.Context

---

docs/source/changelog/bugfix/detector_size_error_msg.rst
docs/source/changelog/obsolescence/detector_size_raw.rst
src/libertem/io/dataset/raw.py
tests/io/test_raw.py
tests/test_context.py

Better error message when parameter detector_size is missing.
Fix #600

Fix issue 600

---

docs/source/releasing.rst

Added items mentioned in issue #629

Add items to release checklist

---

docs/source/changelog/misc/progress_bar_support.rst
src/libertem/api.py

Added progress bar support for `Context.map` and `Context.run`
fix #644

Added progress bar support

---

.travis.yml
mypy.ini
src/libertem/api.py
src/libertem/masks.py
src/libertem/udf/base.py
tox.ini

Use type system parameter

---

README.rst
docs/source/changelog/documentation/venv_doc.rst
docs/source/install.rst

Generalised virtualenv creation for different
python version.
Added a optional instruction for installing pytorch.

Improved installation docs

---

docs/source/udf.rst
docs/source/udf/advanced.rst
src/libertem/udf/sum.py

* Initialize MaxUDF with `-inf`, correct neutral element for `max()`
* Use dtype system
* Clarify documentation of `process_frame()`

Small UDF fixes

---

src/libertem/udf/stddev.py

Counter stability issues with this algorithm
Closes #657

Perform calculation in float64

---

packaging/creators.json
scripts/creatorlist.ipynb

* Ordering following authorship policy

Script to create formatted author list; reorder creators.json

---

docs/source/references-libertem.bib
docs/source/usage.rst

Citation for dataset used in screenshot
is added.

Added citation of dataset used

---

packaging/zenodo-upload.json

Closes #676
Tested successfully on Zenodo sandbox

[skip CI] Add communities to Zenodo template

---

test_requirements.txt
tox.ini

Add pytest-xdist

---

src/libertem/web/cli.py

Thx @sk1p , good catch!
Refs #546 #685

Not necessary to set environment variables anymore

---

src/libertem/api.py
src/libertem/web/connect.py

Changing the default Dask cluster can have unwanted and unexpected side
effects for users.

Don't set as default Dask cluster

---

docs/publications/joss/paper.bib
docs/source/changelog.rst
docs/source/changelog/documentation/modify_doc.rst
docs/source/debugging.rst
docs/source/references-libertem.bib
docs/source/sample_datasets.rst
docs/source/udf.rst
docs/source/udf/advanced.rst
src/libertem/analysis/base.py
src/libertem/api.py
tox.ini

Update the sample dataset section. Thx @twentyse7en and @sayandip18 for the build up!
Additional smaller fixes such as updating the book chapter BibTeX entry.

Sample datasets; reference for book chapter; misc docs

---

docs/source/acknowledgments.rst
packaging/contributors.json
packaging/creators.json

Updated credits with Swift hackathon and ptychography meeting

---

.github/PULL_REQUEST_TEMPLATE
docs/source/api.rst
docs/source/formats.rst
docs/source/usage.rst
packaging/contributors.json
packaging/creators.json

* Reference to sample data section, closes #588 
* Update creators.json
* Update PR template, closes #646

Various documentation fixes

---

README.rst
docs/source/changelog/documentation/update_file_formats.rst
packaging/creators.json

Update file formats

---

src/libertem/io/dataset/base/dataset.py

Fixing typo

---

docs/source/contributing.rst

Add link to GitHub PR video

---

.github/PULL_REQUEST_TEMPLATE
docs/source/contributing.rst

Doc changes to prevent conflicts due to including rebuilt client build

---

tests/conftest.py
tox.ini

Increase http_client timeout, refs #713

---

src/libertem/udf/stddev.py

stddev: Assume constant tiling only within partition

---

docs/source/changelog/bugfix/reduce_udf_overhead.rst
src/libertem/executor/base.py
src/libertem/executor/dask.py
src/libertem/executor/inline.py
src/libertem/udf/base.py

Reduce UDF result overhead

---

docs/source/changelog/bugfix/remote.rst
src/libertem/io/dataset/blo.py
src/libertem/io/dataset/dm.py
src/libertem/io/dataset/empad.py
src/libertem/io/dataset/raw.py

Fix cross-platform dataset opening

---

docs/source/changelog/bugfix/autoremote.rst
docs/source/tips.rst
prototypes/reproducers/crossplatform-opening.ipynb
src/libertem/io/dataset/hdf5.py

Fix cross-platform file type autodetection

---

packaging/contributors.json
packaging/creators.json

Ordering, GSoC 2020, credit Terri from PSF
CC @terriko with thanks :-)

Update author info

---

docs/source/releasing.rst
setup.cfg
tests/server/test_browse.py
tests/server/test_cancel.py
tests/server/test_dataset.py
tests/server/test_download.py
tests/server/test_ds_detect.py
tests/server/test_job.py
tests/server/test_startup.py
tests/server/test_state.py

* Mark them
* Exclude them
* Correct "-m ..." switch
* Include in release checklist

Exclude flaky tests

---

src/libertem/io/dataset/ser.py

Fix remote file opening in SER

---

docs/source/api.rst
docs/source/citing.rst
docs/source/concepts.rst
docs/source/contributing.rst
docs/source/formats.rst
docs/source/install.rst
docs/source/reference/dataset.rst
docs/source/releasing.rst
docs/source/tips.rst
docs/source/udf.rst
docs/source/usage.rst
src/libertem/analysis/base.py
src/libertem/api.py
src/libertem/web/server.py

Many small tweaks all over the place...

Docs review

---

docs/source/api.rst
docs/source/changelog.rst
docs/source/udf.rst
docs/source/udf/profiling.rst

Still reviewing, but can be merged any time :-)

Docs review cont.; Post release change log update

---

docs/source/sample_datasets.rst

HDF5 sample dataset

---

docs/source/changelog/features/log_lvl_cli.rst
docs/source/usage.rst
src/libertem/web/cli.py
src/libertem/web/server.py

Logging level can be configured from cmd line, default INFO.
fix #743

Cmd line argument to set log level

---

docs/source/changelog/bugfix/empty_roi_and_extra_shape_with_zero.rst
docs/source/sample_datasets.rst
src/libertem/common/buffers.py
src/libertem/udf/base.py
tests/udf/test_pick.py
tests/udf/test_simple_udf.py

Handle empty ROI and extra_shape with zero

---

packaging/contributors.json

CC @jhgee with thanks :-)
Refs #153 #767

Acknowledge John Gaida

---

README.rst

CC @bdalevin  :-)
Refs #767 #153

Update README.rst with Norpix SEQ

---

.travis.yml
docs/source/changelog/misc/numba.rst
packaging/docker/Dockerfile
setup.py
src/libertem/utils/threading.py

Refs https://github.com/LiberTEM/LiberTEM/pull/685#issuecomment-625939720

Use thread control for Numba

---

docs/source/acknowledgments.rst
docs/source/changelog/misc/confirm_exit.rst
src/libertem/io/dataset/base/utils.py
src/libertem/web/server.py

Ask for confirmation if the user press ctrl+c.
can immediately stop using another ctrl+c.
willn't work on windows.
fixes #762

Confirm message for ctrl+c

---

src/libertem/udf/base.py

Add simple docstring to `get_tiling_preferences`

---

pytest.ini
setup.cfg
tests/utils.py
tox.ini

Mostly adding timestamps to the relevant parts and configuring pytest to include timestamps in the logging format.

Better test debug logging

---

docs/publications/joss/paper.bib
docs/publications/joss/paper.md
packaging/creators.json

* Remove performance claims compared to Spark and dask.distributed -- refs #198
* Suggestions by @majensen, thx! :-)
@AnandBaburajan @twentyse7en @abiB27 @bdalevin @Iamshankhadeep @saisunku you started contributing to LiberTEM after the first draft of this paper was submitted. Since you became co-creators of LiberTEM and the paper now references the latest release 0.5.0, per our authorship policy you are cordially invited to be co-authors of this paper!
See also https://github.com/openjournals/joss-reviews/issues/2006 for the open review.

Final adjustments for JOSS paper

---

docs/publications/joss/paper.md
packaging/creators.json

Add @sayandip18 to JOSS co-authors; add orcid

---

src/libertem/udf/base.py

This is a complex and performance-critical part of the UDF interface.
Refs #814

Remove nested function in UDFRunner to facilitate profiling

---

src/libertem/executor/dask.py
tests/corrections/test_detector.py

Don't accidentally catch exceptions

Make the `correct` tests a bit more strict

---

docs/source/concepts.rst

Make sub level headlines to remove from left column TOC

---

docs/publications/joss/paper.bib

Starting by submitting an incomplete pull request (PR) or draft PR is OK. You
can work on the checklist step by step by pushing additional commits into the
PR. Please indicate if you think some items may not be applicable.
You can have a look at [our contributing
docs](https://libertem.github.io/LiberTEM/contributing.html) for more
information on contributing to LiberTEM. Please feel free to ask for
clarification and help, for example in your PR description, with comments or in
our [Gitter channel](https://gitter.im/LiberTEM/Lobby).
Thank you for your contribution!

small changes to fix cases in booktitles in bib

---

docs/publications/joss/paper.bib

Starting by submitting an incomplete pull request (PR) or draft PR is OK. You
can work on the checklist step by step by pushing additional commits into the
PR. Please indicate if you think some items may not be applicable.
You can have a look at [our contributing
docs](https://libertem.github.io/LiberTEM/contributing.html) for more
information on contributing to LiberTEM. Please feel free to ask for
clarification and help, for example in your PR description, with comments or in
our [Gitter channel](https://gitter.im/LiberTEM/Lobby).
Thank you for your contribution!

one more bib fix

---

README.rst

Add JOSS badge to README

---

src/libertem/analysis/fullmatch.py

Make test success not depend on numerical noise close to zero

---

.travis.yml
conftest.py
packaging/docker/Dockerfile
packaging/docker/docker-compose.yml
packaging/docker/requirements.txt
tests/test_ipython.py

Test on ipyparallel

---

README.rst

Follow-up of the move to travis-ci.com: fix badge link, re-order

---

src/libertem/io/dataset/ser.py

Was removed upstream and not explicitly used by LiberTEM, anyways.

SER: don't use emifile argument anymore

---

docs/source/usage.rst

Add a note about browsers we test on

---

tests/corrections/test_detector.py
tests/io/test_tiling_negotiation.py

Fix some warnings in test code

---

conftest.py
src/libertem/analysis/com.py
src/libertem/analysis/sd.py
src/libertem/web/generator.py
tests/template/test_com_template.py
tests/template/test_disk_template.py
tests/template/test_fem_template.py
tests/template/test_fft_template.py
tests/template/test_pick_template.py
tests/template/test_point_template.py
tests/template/test_radial_fourier_template.py
tests/template/test_ring_template.py
tests/template/test_sd_template.py
tests/template/test_sum_template.py

Fix issue #854 , #855 
Also, notebook naming is fixed.

Fix COM plotting and ROI in SD analysis

---

src/libertem/analysis/sumsig.py
tests/template/test_fft_template.py
tests/template/test_sumsig_template.py

Added the tests for `SumSigAnalysis` and `PickFFTFrameAnalysis`
notebook generation.

Add the missing tests for Template

---

src/libertem/udf/stddev.py

Fix "Inline literal start-string without end-string" in newest Sphinx

---

docs/source/changelog.rst

Update changelog for 0.5.1, including zenodo badge

---

tox.ini

Fixes incompatibility of latest sphinx-autobuild release. Thanks @sayandip18 for reporting in the gitter channel!

Fix sphinx-autobuild invocation from tox

---

docs/source/dist_tests.rst

Fix typo in docs

---

.dockerignore
README.rst
docs/source/changelog/features/mrc-support.rst
docs/source/formats.rst
docs/source/reference/dataset.rst
packaging/docker/docker-compose.yml
src/libertem/io/dataset/__init__.py
src/libertem/io/dataset/base/backend.py
src/libertem/io/dataset/mrc.py
tests/io/datasets/test_dm.py
tests/io/datasets/test_empad.py
tests/io/datasets/test_frms6.py
tests/io/datasets/test_k2is.py
tests/io/datasets/test_mib.py
tests/io/datasets/test_mrc.py
tests/server/test_copy.py
tests/utils.py
tox.ini

MRC DataSet support

---

src/libertem/common/container.py
src/libertem/udf/masks.py
tests/test_analysis_masks.py

* Solve deprecation warning for import location cupy->cupyx
* Hopefully temporary workaround for https://github.com/cupy/cupy/issues/4072
Not sure why this wasn't triggered before!

Test masks with CuPy

---

packaging/docker/Dockerfile

Try fixing #883 by installing ipyparallel master branch instead of fork

---

src/libertem/io/dataset/hdf5.py
src/libertem/web/notebook_generator/code_template.py
src/libertem/web/notebook_generator/template.py
tests/template/temp_utils.py
tests/template/test_ring_template.py

Fix to generate TCP cluster connection in the notebook template.

Fix cluster code in notebook

---

tests/template/test_radial_fourier_template.py

Create radial fourier analysis once.

Fix radial fourier template test

---

benchmarks/corrections/test_corrset.py
benchmarks/io/test_mib.py
conftest.py
docs/source/changelog/bugfix/corrections.rst
src/libertem/analysis/clust.py
src/libertem/analysis/point.py
src/libertem/common/numba.py
src/libertem/corrections/corrset.py
src/libertem/corrections/detector.py
src/libertem/io/dataset/base/tiling.py
src/libertem/udf/base.py
src/libertem/utils/generate.py
tests/corrections/test_corrset.py
tests/corrections/test_detector.py
tests/utils.py

Quick and dirty reproducer for the error message in #889 - does not yet reproduce the numba compilation performance issues.
@uellue feel free to push into this branch if you have ideas for benchmark or fix.

Fix corrections for many pixels

---

azure-pipelines-data.yml
azure-pipelines.yml
conftest.py
tests/aio_utils.py
tests/server/test_browse.py
tests/server/test_cancel.py
tests/server/test_copy.py
tests/server/test_download.py
tests/server/test_ds_detect.py
tests/server/test_job.py
tests/server/test_startup.py
tests/template/test_com_template.py
tests/template/test_disk_template.py
tests/template/test_fem_template.py
tests/template/test_fft_template.py
tests/template/test_pick_template.py
tests/template/test_point_template.py
tests/template/test_radial_fourier_template.py
tests/template/test_ring_template.py
tests/template/test_sd_template.py
tests/template/test_sum_template.py
tests/template/test_sumsig_template.py

- Adding caching for pip packages
- Try to fix the trigger for the master branch

Update azure pipelines

---

azure-pipelines.yml
conftest.py
scripts/release
tests/server/test_dataset.py
tests/server/test_startup.py
tests/template/test_clust_template.py
tests/template/test_com_template.py
tests/template/test_disk_template.py
tests/template/test_fem_template.py
tests/template/test_fft_template.py
tests/template/test_pick_template.py
tests/template/test_point_template.py
tests/template/test_radial_fourier_template.py
tests/template/test_ring_template.py
tests/template/test_sd_template.py
tests/template/test_sum_template.py
tests/template/test_sumsig_template.py

- Run release script verbosely
- Cache for npm and pip deploy_docs
- Some more local cluster re-use

More azure pipeline updates

---

tests/corrections/test_detector.py

Closes #910
Nice edge case btw!

Make sure the damaged data is different from the corrected

---

.github/PULL_REQUEST_TEMPLATE

Include running the data pipeline in PR template

---

benchmarks/common/test_numba.py
docs/source/changelog/bugfix/point_analysis.rst
prototypes/sparse-comparison/apply_point_selector_BiFeO3-tiled.ipynb
src/libertem/common/numba.py
src/libertem/udf/masks.py
test_requirements.txt
tests/common/test_numba.py
tests/test_analysis_masks.py

...for scipy.sparse.{csc,csr]_matrix
Closes #917
See also https://github.com/scipy/scipy/issues/13211

Custom right hand side matrix multiplication

---

benchmarks/common/test_numba_warmup.py
src/libertem/common/numba.py
src/libertem/io/dataset/base/backend.py
src/libertem/io/dataset/base/tiling.py
src/libertem/io/dataset/mib.py
src/libertem/web/dataset.py
tests/common/numba_cache.py
tests/common/test_numba.py

JIT caching continuation

---

src/libertem/executor/dask.py
tests/server/test_cluster_status.py

Try to wait_for_workers in make_local

---

src/libertem/io/fs.py

Handle an empty DVD drive on Windows gracefully

---

docs/source/changelog.rst

Changelog: note that GPU support is experimental

---

docs/source/changelog.rst
docs/source/reference/io_backends.rst
packaging/contributors.json
packaging/creators.json

Augment Authors Contributors; docs touchup

---

README.rst
docs/source/contributing.rst
docs/source/dev/setup.rst
docs/source/install.rst
docs/source/releasing.rst
docs/source/tips.rst
docs/source/udf/profiling.rst

Use `python -m pip`

---

src/libertem/executor/dask.py

Closes #574 
* Updated `run_tasks`, `run_function`, and `map`

Don't assume pure functions in `DaskJobExecutor`

---

docs/source/changelog.rst
docs/source/changelog/features/udf-get-results.rst
docs/source/concepts.rst
docs/source/udf/advanced.rst
pytest.ini
src/libertem/analysis/apply_fft_mask.py
src/libertem/analysis/clust.py
src/libertem/analysis/sd.py
src/libertem/common/buffers.py
src/libertem/udf/base.py
src/libertem/udf/stddev.py
tests/common/test_bufferwrapper.py
tests/executor/test_dask.py
tests/template/test_sd_template.py
tests/udf/test_simple_udf.py

Add `UDF.get_results` method that is called on the master node after each merge. Fixes #628
Note that for the `StdDevUDF`, the implementation is completely backwards-compatible - this is a bit awkward, as the arrays are returned either as `ndarray` or as `BufferWrapper` . Other UDFs may have similarly decisions to make. Especially with `roi`s this may be a bit problematic - the UDF has to decide if it wants to return the derived result as `raw_result`-like array, or embedded into a `NaN`-filled array.
For other UDFs, where backwards-compatibility is not a concert, `get_results` can now return `BufferWrapper`s, too:
```python
def get_results(self):
return {'derived': self.result(name='derived', data=np.log1p(self.buffers.original)}
```
The repetition of `name='derived'` is a bit …

Support for a final postprocessing on main node

---

docs/source/packages.rst

Include link to Ptychography 4.0 in package overview

---

docs/source/changelog/documentation/gms.rst
examples/digital-micrograph-cluster.py
examples/digital-micrograph-local.py

The cluster start-up takes a long time, however, so the other methods work better.
Follow-up to #1002 

Figured out how to start a local cluster

---

tests/io/datasets/test_frms6.py
tests/io/datasets/test_k2is.py

These tests are run, if the reference is there, in the default
`pytest tests/` invocation. So they considerably slow down the test runs
for me - mostly because `np.allclose` is quite slow. I see two "fixes"
for this:
1) Don't run the comparison tests by default, mark them "slow" or similar
2) Use a faster comparison function. I would argue that we can require
equality instead of allowing a tolerance in these cases.
On one hand, because we are reading the data as integers anyways
(so it boils down to a `memcmp`), and on the other hand, if we were
to convert to `float32`, there still shouldn't be a difference,
because the numbers in range for these formats can easily be
represented without loss of precision.
I've opted for option 2 for now, because routinely running these tests in …

Speed up `test_comparison{,_roi}` for K2IS and FRMS6

---

docs/source/tips.rst

Fix headline hierarchy

---

azure-pipelines-data.yml
azure-pipelines.yml
packaging/docker/Dockerfile
packaging/docker/requirements.txt
setup.py
tox.ini

Closes #914
Documentation and changelog will be handled in #1034 

Support Python 3.9

---

packaging/appimage/make_app_image.sh

Use Python 3.9 for the AppImage

---

docs/source/changelog.rst
docs/source/releasing.rst

Fixes #985
* Date and DOI
* Update release checklist drive-by

Post-release changelog update

---

src/libertem/io/dataset/seq.py
tests/io/datasets/test_seq.py

SEQ: use executor for detect_params

---

README.rst
azure-pipelines-data.yml

- Disable `htmlcov` uploads for data tests
- Add pre-commit.ci badge

More CI updates

---

docs/source/changelog/bugfix/dmdataset_files_checking.rst
packaging/creators.json
src/libertem/io/dataset/dm.py
tests/io/datasets/test_dm.py

References Issue https://github.com/LiberTEM/LiberTEM/issues/1055
I can't run the tests on the IO code due to lack of access. I don't imagine the one line assert will cause a problem though!

Add files= argument checking to DMDataset

---

docs/source/changelog/bugfix/numba_compat_fixes.rst
src/libertem/common/numba/__init__.py
src/libertem/common/numba/cache.py
tests/common/test_numba.py
tests/viz/test_bqp.py

Fix compatibliity with numba 0.54

---

.pre-commit-config.yaml
azure-pipelines.yml
scripts/release
src/libertem/corrections/detector.py
tests/common/test_numba.py
tests/corrections/test_corrset.py
tests/corrections/test_detector.py
tests/io/test_cached.py
tests/server/test_copy.py
tests/template/test_clust_template.py
tests/template/test_radial_fourier_template.py
tests/template/test_sd_template.py
tests/test_analysis_clust.py
tests/test_analysis_masks.py
tests/udf/test_stddev.py

Adds parameters that allows recreating the tox environment, and/or run slow tests:
This is meant for more comprehensive testing before cutting a release. Some additional tests that took over 10 seconds on any of the platforms are now also marked as slow.
This also disables some of the Azure specific code coverage reporting, as that is sometimes really slow. In general, it appears that some of the jobs are just scheduled on systems that are I/O overloaded - even checking out the source code, unpacking the pip cache etc. takes a long time sometimes:
Refs #1045

Cache tox environments on Windows and Mac OS X

---

docs/source/changelog/documentation/hdf5plugin_note.rst
src/libertem/io/dataset/hdf5.py

closes https://github.com/LiberTEM/LiberTEM/issues/1054

Documentation note for custom compressed HDF5 datasets

---

nbval_sanitize.cfg
tests/io/datasets/test_seq.py

Also sneaking in a fix for the nbval normalization regexes

SEQ: disable corrections for comparison tests

---

docs/source/tips.rst

Include "gotcha" for bqplot on JupyterHub

---

docs/source/changelog/misc/xml_readings_defusedxml.rst
src/libertem/io/dataset/empad.py
tests/io/datasets/test_empad.py

xml reading library changed to defusedxml

---

docs/source/changelog/bugfix/numbathreads.rst
src/libertem/utils/threading.py
tests/executor/test_dask.py

Unset environment variables properly after setting thread count

---

packaging/docker/Dockerfile
packaging/docker/requirements.txt
packaging/docker/update_reqs.sh

It now installs the current ipyparallel from pypi instead of the unreleased git version.
Refs #484

Update docker packaging for dist testing

---

src/libertem/common/buffers.py
tests/common/test_bufferwrapper.py

Confirm that the views have the expected shape.
Refs #1026

Defend against out of bounds slices

---

docs/source/changelog.rst
docs/source/changelog/bugfix/coords.rst
docs/source/changelog/bugfix/memleak-fn-caching.rst
docs/source/changelog/misc/scheduler.rst
docs/source/changelog/misc/threadcount.rst
packaging/zenodo-upload.json
src/libertem/udf/base.py

Finishing touches for release

---

docs/source/changelog.rst

DOI badge for 0.8.0

---

docs/source/releasing.rst

Update release checklist

---

src/libertem/udf/base.py
tests/udf/test_meta.py

Fix failure in ptychography40 SSB_UDF
No changelog entry since the change was introduced after 0.8.0

Make sure self.meta is available as soon as possible

---

azure-pipelines.yml
packaging/docker/release.sh
scripts/release
scripts/requirements.txt

Also, run the script in CI at least in husk form for PRs

Fix docker deployment in CI

---

docs_requirements.txt
nbval_sanitize.cfg
tox.ini

To fix our tests with data access. Extracted from #1170 (without the hyperspy integration notebook, of course). author: @uellue

Fix pyxem tests

---

src/libertem/io/dataset/mib.py
src/libertem/io/dataset/tvips.py

MIB: fix and document `disable_glob` parameter

---

azure-pipelines-data.yml

As we currently don't have any availability of cloud agents from the
Azure DevOps Pipelines free tier, as a workaround, we are using our own
agent for all tests. This means:
- We currently can't run Windows / Mac OS X tests in CI
- We can't run any tests that involve docker
- To expand on this: running docker in docker requires, without
additional configuration, that the outer container is started as
privileged. This means that certain capabilities are no longer
dropped by docker, and uid 0 in the inner container is basically
equivalent in privileges to uid 0 outside.
- You can also re-use the "host" docker daemon by mounting the
docker socket into the container, but that too is a security
issue, as then the container can start other containers which
can mount arbitrary file system paths. …

Move all CI jobs to self-hosted Azure Agent

---

azure-pipelines-data.yml
codecov.yml
scripts/codecov.sh

- Use the new statically linked binary codecov uploader
- Configure codecov to only comment after 11 build job results have arrived
- Fixup for app images: cleanup before building the new app image
Fixes #1190

codecov updates

---

README.rst
docs/source/changelog.rst

Post-release update

---

docs/source/releasing.rst

For example, LiberTEM-live is still a bit alpha quality and uses some internal API, so we should make sure to co-release a LiberTEM-live version that works with the new release.

Update QA checklist: make sure we test integration w/ other packages

---

docs/source/changelog.rst

Co-authored-by: Alexander Clausen <a.clausen@fz-juelich.de>
Fixes #1221

Change log for 0.9.2

---

src/libertem/viz/bqp.py
src/libertem/viz/mpl.py

Ignore NaN for plot range

---

azure-pipelines-data.yml
benchmarks/io/test_hdf5.py
docs/source/conf.py
setup.py
src/libertem/io/corrections/corrset.py
tests/corrections/test_corrset.py
tox.ini

Refs #1133
Additionally, the code is now 100x faster and finds better solutions
in some cases. That's why the tests are adjusted.
* [-] `/azp run libertem.libertem-data` passed

Remove dependency on primesieve

---

azure-pipelines-data.yml

Run on more Python versions, creating a more complete matrix etc. Fixes #1265

Thorough CI if `run_slow` is set

---

docs_requirements.txt

Pin sphinx to <5.1

---

conftest.py
docs/source/api.rst
docs/source/changelog/features/empad-series.rst
docs/source/changelog/features/npy_datset.rst
docs/source/changelog/features/pipelined-executor.rst
docs/source/dev/executors.rst
setup.py
src/libertem/api.py
src/libertem/common/executor.py
src/libertem/executor/concurrent.py
src/libertem/executor/dask.py
src/libertem/executor/delayed.py
src/libertem/executor/inline.py
src/libertem/executor/pipelined.py
src/libertem/executor/utils/shmqueue.py
src/libertem/io/dataset/base/dataset.py
src/libertem/io/dataset/base/partition.py
src/libertem/udf/base.py
src/libertem/web/cli.py
tests/executor/test_functional.py
tests/executor/test_pipelined.py

This code is not fully benchmarked and battle tested yet, but works well together with corresponding changes in LiberTEM-live in the DECTRIS branch. Not optimized for offline processing at all, yet.

Pipelined executor

---

docs/source/changelog/bugfix/pipelined-restart.rst
src/libertem/common/executor.py
src/libertem/executor/pipelined.py

Restart worker pool after running into error state

---

docs/source/changelog/bugfix/pipelined-queue.rst
setup.cfg
src/libertem/common/executor.py
tests/executor/test_executor_base.py

Drive-by: Fix installation in X-Spectrum dev environment
TODO: Test case, possibly changelog?

Fix SimpleMPWorkerQueue.put_nocopy()

---

docs/source/changelog/bugfix/stddev.rst
src/libertem/udf/stddev.py
tests/udf/test_stddev.py
tests/utils.py

* A few absolute values were missing
Fortunately this is an edge case since we hardly process any complex input data!

Fix standard deviation for complex input data

---

docs_requirements.txt
test_requirements.txt
tox.ini

Pin orix/joblib/... to compatible versions

---

conftest.py
docs/source/changelog/bugfix/context-cleanup-atexit.rst
src/libertem/api.py
src/libertem/executor/dask.py
src/libertem/executor/pipelined.py
tests/executor/test_pipelined.py
tox.ini

Fixes #1339
It registers an atexit handler with a weak reference to the `Context`, and calls `Context.close` at process exit. Usually, using
with Context(...) as ctx:
...
or explicitly calling `Context.close` for cleanup is preferred, but it is not obvious, and also not consistent with notebook usage, where a context manager is not practical.
Tests TBD - not sure yet how to properly test this. Sketch: maybe with a small function ran via `multiprocessing.Process(target=...)`, and two cases; 1) manual cleanup before interpreter shutdown, 2) automatic `atexit` cleanup. Both should complete within reasonable time limits.
Maybe the `__del__` of `PipelinedExecutor` should be completely removed, as it can lead to these confusing error messages?
* [N/A] I have added/updated documentation for all …

Make sure the `Context` cleans up after itself

---

tests/executor/test_pipelined.py

test_pipelined: increase timeout for joining in manual teardown test

---

src/libertem/executor/pipelined.py
src/libertem/io/dataset/hdf5.py

* HDF5 reader performance fix
* Pipelined executor fixes

Desysession

---

docs/source/changelog/misc/other_progress.rst
docs/source/reference/index.rst
docs/source/reference/progress.rst
src/libertem/api.py
src/libertem/common/progress.py
src/libertem/executor/delayed.py
src/libertem/udf/base.py
tests/common/test_progress.py

This is a component of the progress bar PR ( #1341 ) which probably should have been included then. We added plumbing for the `UDFRunner` to inject other types of `ProgressReporter` (the object which actually displays the progress messages), but didn't expose any user-facing endpoints. This is because `UDFRunner` is implicitly instantiated by `ctx::_run_sync_wrap` with only the `udfs` argument. You can get around it by subclassing the particular Executor + UDFRunner you're using but it's heavy!
This commit is the simplest possible suggestion to solve this, we essentially leave it to the user to ensure that whatever they pass into Context will forever be viable as a way to display progress, either as an object which can be re-used or a class which can be forever re-instantiated by the …

Add endpoint to set progress reporter

---

.github/workflows/trigger-pages-rebuild.yml

Makes sure the contributor lists are kept up to date.

Trigger libertem.github.io rebuild on push to master

---

benchmarks/io/test_dask.py
client/package.json
docs/source/releasing.rst
src/libertem/io/dataset/base/file.py
src/libertem/io/dataset/dm.py
src/libertem/io/dataset/dm_single.py
tests/executor/test_functional.py
tests/io/datasets/test_dm.py

Pick a few low-hanging fruits.
Closes #1290 
Closes #1300
Closes #1383 
Closes #1389 

Misc fixes for release

---

docs/source/references-libertem.bib
docs/source/sample_datasets.rst
src/libertem/udf/masks.py
src/libertem/udf/raw.py
src/libertem/udf/stddev.py
src/libertem/udf/sum.py

Misc. documentation fixes
- Removing methods from the documentation that are not useful for users or even misleading
- Adding some examples
@uellue @matbryan52 feel free to push any doc fixes that should be part of 0.11 into this PR.
* [N/A] No import of GPL code from MIT code

WIP: misc docs improvements

---

docs/source/contributing.rst
docs/source/dev/setup.rst
src/libertem/io/dataset/raw_csr.py

There's one unresponsive server which I just kept as-is

Link check

---

prototypes/webrtc/README.rst
prototypes/webrtc/client.js
prototypes/webrtc/draw_webrtc.py
prototypes/webrtc/index.html
prototypes/webrtc/jupyter-test.ipynb
prototypes/webrtc/server.py

Based on https://github.com/aiortc/aiortc/tree/main/examples
Create a video stream from a changing NumPy array on a server and receive it in the browser. This could be the basis for very fast low-latency live plots over network.

WebRTC stream prototype

---

azure-pipelines-data.yml
scripts/release
scripts/requirements.txt

Extracts some variables for easier merging and adds initial github actions support.
Also performs additional sanity check when bumping the version (newer version must be larger)

Sync release script with LiberTEM-blobfinder

---

azure-pipelines-data.yml
docs/source/install.rst
setup.py
tox.ini

To get Python 3.11 support started. We might want to discuss further CI improvements and/or thinning of our default test matrix for faster runs.

Test on Python 3.11

---

src/libertem/preload.py
tests/common/test_numba.py

Workaround for regression in numba 0.57.0

---

.github/workflows/ci.yml
MANIFEST.in

This is needed to use tox to run tests directly from the sdist.
Also exclude `mypy_cache` and `__pycache__` directories.
Similar to https://github.com/LiberTEM/LiberTEM-live/pull/114

Add missing override_requirements.txt to MANIFEST.in

---

docs/source/dev/setup.rst
docs/source/formats.rst
docs/source/install.rst
docs/source/reference/dataset.rst
examples/basic.py
src/libertem/io/dataset/dask.py
src/libertem/io/dataset/empad.py
src/libertem/io/dataset/frms6.py
src/libertem/io/dataset/k2is.py
src/libertem/io/dataset/memory.py
src/libertem/io/dataset/npy.py
src/libertem/io/dataset/raw_csr.py

More docs improvements (for after release)

---

docs/source/changelog/features/pipeline-scheduling.rst
src/libertem/common/executor.py
src/libertem/executor/pipelined.py
tests/executor/test_pipelined.py

As [discussed before](https://github.com/LiberTEM/LiberTEM/pull/1267/files#r927542348) , an easy improvements on the round-robin scheduling implemented before, is sending tasks always to the process with the shortest request queue. This is implemented in these changes.
This should improve GPU performance, too, although I have not benchmarked this yet. With these changes, it should also be quite easy to preferentially send tasks to GPU workers when they are idle. Implementing proper resource support should now also be possible (see #1453).
In addition, this also speeds up the tests by a lot; on the system I tested a full `tests_pipelined` run goes from ~108s to ~28s - by using less worker processes, and by catching errors on startup faster. Also marked the "default spec" case as slow, as …

Improved scheduling for the `PipelinedExecutor`

---

docs/source/changelog.rst

Add changelog entry for point release v0.11.2

---

conftest.py
docs/source/changelog/bugfix/raw_csr_uint64.rst
src/libertem/io/dataset/raw_csr.py
tests/io/datasets/test_raw_csr.py

Support and test indptr with dtype uint64

---

docs/source/changelog/features/sparse.rst
docs/source/udf/advanced.rst
src/libertem/common/udf.py
src/libertem/udf/base.py
src/libertem/udf/masks.py
src/libertem/udf/stddev.py

Avoid interacting with sparseconverter directly in UDFs. See https://github.com/Ptychography-4-0/ptychography/pull/68#discussion_r1236883612 for rationale!

Re-export categories from sparseconverter

---

packaging/appimage/make_app_image.sh
tests/executor/test_functional.py

- Use Python 3.11
- Build using `python -m build`
- Hopefully fix flakyness of `test_scatter_update`

Update AppImage build process

---

src/libertem/common/executor.py
src/libertem/executor/pipelined.py
src/libertem/udf/base.py
tests/executor/test_functional.py

- More visibility into tasks of the pipelined executor: among other details, trace queue puts, as they can take a bit of time for larger values
- Fix execution plan tracing event - can't have an `OrderedDict` as value, so format as `List[str]`

Improve tracing

---

docs/source/changelog/features/dtype-diags.rst
src/libertem/io/dataset/mrc.py
src/libertem/io/dataset/npy.py
src/libertem/io/dataset/raw.py
src/libertem/io/dataset/raw_csr.py
tests/io/datasets/test_mrc.py
tests/io/datasets/test_npy.py
tests/io/datasets/test_raw.py
tests/io/datasets/test_raw_csr.py

Add dtype diagnostics for some dataset impls

---

docs/source/changelog/features/gcxs.rst
src/libertem/common/container.py
tests/analysis/test_analysis_masks.py

Support sparse.GCXS in MaskContainer

---

setup.py

Fixes #1490; workaround for https://github.com/hhatto/autopep8/issues/689

Pin pycodestyle

---

packaging/creators.json

* [N/A ] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)
* [N/A ] `/azp run libertem.libertem-data` passed
* [N/A] No import of GPL code from MIT code

Author ordering

---

README.rst
docs/source/changelog.rst

Sneaky late addition to the changelog, as this is the first major release with distribution on `conda-forge`. Also adds conda-forge and pypi badges to the readme as a drive-by.

Add note on `conda-forge` to changelog, add badges to readme

---

docs_requirements.txt

Works around https://github.com/domdfcoding/enum_tools/issues/77

Pin sphinx to <7.2

---

src/libertem/web/server.py

Add route for /assets/

---

codecov.yml

See discussion here: https://community.codecov.com/t/upload-issues-unable-to-locate-build-via-github-actions-api/3954
Since there's really no better solution, this PR hardcodes a codecov token to increase the success rate of coverage uploads.
>Public repositories that rely on PRs via forks will find that they cannot effectively use Codecov if the token is stored as a GitHub secret. The scope of the Codecov token is only to confirm that the coverage uploaded comes from a specific repository, not to pull down source code or make any code changes.
>For this reason, we recommend that teams with public repositories that rely on PRs via forks consider the security ramifications of making the Codecov token available as opposed to being in a secret.
>A malicious actor would be able to upload …

Add hardcoded codecov token

---

tracing/.env
tracing/docker-compose.yml
tracing/otel-collector-config.yaml

Following
https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/examples/demo
Closes #1540 

Update tracing setup

---

scripts/releasetests.ps1
tox.ini

* Include cuda12x
* Allow to run notebook tests with CUDA (to be tested more)
* [N?A] I have included the [rebuilt production build of the client](https://libertem.github.io/LiberTEM/contributing.html?#building-the-client) (only if changes were made to the GUI)

Update tox.ini and add Powershell script for release tests

---

README.rst
docs/source/app/amorphous.rst
docs/source/contributing.rst
docs/source/debugging.rst
docs/source/packages.rst
setup.py
src/libertem/api.py
src/libertem/udf/stddev.py

The removed one on symmetry was already dead for 0.12. I couldn't find an alternative source, unfortunately.
Edit: Include new link from @sk1p and a few other docs fixes

Docs fixes

---

docs/source/releasing.rst
setup.py
tests/io/datasets/test_frms6.py
tests/server/test_cancel.py

* Hopefully resolve flakiness in https://github.com/LiberTEM/LiberTEM/issues/1542#issuecomment-1802198118
* Resolve version incompatibility on Python 3.7
* Closes #1552

Misc release testing

---

README.rst

Switch from Docker hub to GHCR

---

docs/source/changelog.rst
docs/source/changelog/features/convert_transposed.rst
docs/source/changelog/features/gui-gpu-workers.rst
docs/source/changelog/features/gui-progress-bar.rst
docs/source/changelog/features/gui-resource-cli.rst
docs/source/changelog/features/gui-url-trigger-open.rst
docs/source/changelog/features/shifted.rst
docs/source/changelog/features/udf_method_choice.rst
docs/source/changelog/misc/exceptions.rst
docs/source/changelog/misc/hashable_shape.rst

Release 0.13.0 doc updates + Changelog

---

docs/source/releasing.rst

...so that users can upgrade immediately

Release on conda-forge before e-mail

---

.github/workflows/ci.yml
azure-pipelines-data.yml
docs/source/install.rst
setup.py
test_requirements.txt

~~Test with the numba release candidate; can be merged once that is properly released.~~

Support Python 3.12

---

.github/dependabot.yml

Add weekly dependabot for github actions

---

.github/workflows/ci.yml
codecov.yml

Supersedes #1587 #1588 #1589 #1590

Dependabot rollup

---

.github/workflows/ci.yml

Update nodejs version to current LTS in CI

---

.github/workflows/ci.yml
tests/io/test_many_files.py
tox.ini

Use the just-announced public M1 runners: https://github.blog/changelog/2024-01-30-github-actions-macos-14-sonoma-is-now-available/

Test on M1 / Mac OS 14

---

.github/workflows/ci.yml
azure-pipelines-data.yml
tests/io/datasets/test_blo.py
tests/io/datasets/test_mib.py
tox.ini

Set `uv_seed=True` to keep `pip freeze` working

Try to speed up environment creation using uv + tox-uv

---

src/libertem/executor/dask.py

Cherry-picked from #1578 
Example failure: https://github.com/LiberTEM/LiberTEM/actions/runs/8024972705/job/21924629028
This could be reproduced just by running `test_fd_limit` with a current `dask` version. The different behavior was introduced in dask 2024.2.1 - not sure yet if this is a bug or not, as I haven't managed to minimize the testcase yet.

Work around "UDF run cancelled after 0 partitions"

---

packaging/zenodo-upload.json

The current one maps to GPL 3 only.
Closes #1553 
List of valid license identifier string obtained by
```
import requests
response = requests.get('https://sandbox.zenodo.org/api/licenses/?size=1000')
print(response.json())
```

Update license to GPL 3.0 ~~or later~~ only

---

docs/source/changelog/documentation/airgapped.rst
docs/source/install.rst

Section on air-gapped installation

---

docs/source/architecture.rst
docs/source/changelog.rst
docs_requirements.txt
tests/server/test_cli.py

Misc. docs changes

---

docs/source/changelog.rst

Changelog: DOI and release date

---

docs/source/changelog.rst
docs/source/changelog/bugfix/com.rst
docs/source/changelog/bugfix/empad-scan-params.rst
docs/source/changelog/features/numpy2.rst
docs/source/releasing.rst

Docs update for point release

---

docs/source/changelog.rst

DOI badge for 0.14.1

---

docs/source/changelog/features/mib-scanxy.rst
src/libertem/io/dataset/mib.py
tests/io/datasets/test_mib.py

Merlin: try `ScanX` and `ScanY` from the HDR file

---

src/libertem/io/dataset/npy.py

Follow https://github.com/numpy/numpy/blob/main/numpy/lib/format.py where this code was copied from.

Remove compatibility code

---

docs/source/install.rst

Update doc to recommend Miniforge

---

src/libertem/contrib/daskadapter.py

Improve docstring of `make_dask_array`

---

src/libertem/executor/utils/dask_inplace.py
tests/executor/test_dask_inplace_wrapper.py

Closes #1685 
Two changes:
- Don't try to call `.item()` on a `dask.array.Array` even if it is `size == 1`. This is necessary with numpy arrays to avoid a deprecation warning, but seems like Dask handles this assignment fine.
- Catch a `ValueError` if we try to assign a zero-size value into the dask array, which raises in Dask but is a no-op in Numpy
Also added tests parametrizations which cover these two cases, and by extension the CI failure in #1685, even though I couldn't reproduce exactly that failure myself.
My one concern is how this behaviour changes with older Dask versions....

Fixes in `delayed_inplace_wrapper.py`

---

.github/workflows/ci.yml
.github/workflows/thorough.yml
azure-pipelines-data.yml
docs/source/changelog/features/py313.rst
docs/source/install.rst
pyproject.toml
tox.ini

* Add to CI pipelines
* Add numba minimum version for 3.13

Python 3.13 support

---

src/libertem/common/progress.py
src/libertem/udf/base.py
tests/executor/test_pipelined.py

If we don't, we may swallow exceptions. This should improve reliability (especially the hangs observed recently with Python 3.13).
See #1697 for some additional analysis and stack traces.
Without this, running `pytest tests/executor/test_pipelined.py -n12` on Python 3.13 hung quite reproducibly in `CommsDispatcher.__exit__`, waiting for the `monitor_queue` thread to return. I'm not 100% sure how this hang came to be, but this appears to be fixed by properly propagating exceptions.
(what brought me to this solution: I broke the deadlock by making the `_message_q.get` in `CommsDispatcher.monitor_queue` into a non-blocking variant, and exiting the thread via an event. This showed messages like "Exception ignored in: <generator object ...>", which points to generators not being fully consumed …

Ensure we properly close internal generators/iterators

---

docs/source/changelog/bugfix/idle-cpu-usage.rst
src/libertem/web/event_bus.py

Fix high idle CPU usage cause by busy waiting

---

src/libertem/common/math.py
tests/common/test_math.py

Fix `count_nonzero()`

---

docs/source/changelog/bugfix/idle-cpu-usage.rst
src/libertem/analysis/radialfourier.py
src/libertem/common/progress.py
src/libertem/udf/base.py
src/libertem/web/event_bus.py
tests/analysis/test_analysis_radialfourier.py
tests/executor/test_pipelined.py

Cherry-picked important fixes from #1708 #1715 #1700

Prepare v0.14.2

---

test_requirements.txt
tests/udf/test_execution_plan.py

More prep for v0.14.2

---

docs/source/changelog.rst

Changelog for v0.14.2

---

tests/common/test_snooze.py

Don't sleep for fixed times, wait for messages to appear eventually instead.
Should fix the flaky failure here: https://github.com/LiberTEM/LiberTEM/actions/runs/15300629756/attempts/1

Make `test_messages` more robust

---

src/libertem/executor/dask.py
tests/udf/test_memleak.py

Works around https://github.com/dask/distributed/pull/9045
Possibly related to #1737

Compat for Distributed `scheduler_info` change

---

benchmarks/udf/test_simple_udf.py
conftest.py
docs/source/changelog/features/automonitor.rst
docs/source/changelog/features/maincupy.rst
docs/source/dev/executors.rst
src/libertem/api.py
src/libertem/common/backend.py
src/libertem/common/cupy.py
src/libertem/common/executor.py
src/libertem/common/threading.py
src/libertem/executor/base.py
src/libertem/executor/concurrent.py
src/libertem/executor/dask.py
src/libertem/executor/delayed.py
src/libertem/executor/inline.py
src/libertem/executor/integration.py
src/libertem/executor/pipelined.py
src/libertem/udf/base.py
tests/test_context.py
tests/udf/test_simple_udf.py

* Parameter to `Context.make_with()` to specify GPU
* Activate GPU in relevant parts of `UDFRunner`
* Make available through the `UDF.xp` property
Selecting a GPU in CuPy is confirmed to be thread local. Included tests that confirm correctly setting `UDF.xp` for main process functions without interfering with `UDF.xp` in functions that run on workers.
This change may break UDFs that have previously used `self.xp` on the main node and expected to always receive NumPy. However, given the documentation of `UDF.xp`, users should always expect one of NumPy or CuPy from this property, so no change of documented API behavior.
Drive-by: Fix title of changelog entry; remove duplicate `detect()` call.
* [N/A] I have included the [rebuilt production build of the …

Make GPU processing available on the main process
